FROM node:18
ENV PORT 3000

WORKDIR /usr/src/app/server/

# Copy local .env file
COPY .env /usr/src/app/server/.env

# Installing dependencies
COPY package*.json ./
RUN npm install

# Copying source files
COPY . /usr/src/app/server

# Building app
RUN npm run build
EXPOSE 3000

# Running the app
CMD ["node", "dist/main.js"] 