import { IVideoLink } from '../../users/interfaces/common.interface';
import { CoachBio } from '../interfaces/coach-bio.interface';
import { UserSocialLinksDto } from '../../users/dto/user/user-social-links.dto';
import { CoachRadarSkillsDto } from '../../users/dto/coach/coach-skills.dto';
import { UserTypes } from '../../users/enum/user-types.enum';
import { ILastMatch } from '../../diaries/interfaces/lastMatch.interface';
import { ILastTraining } from '../../diaries/interfaces/lastTraining.interface';

export class CoachBioDto implements CoachBio {
  userId: string;
  lastUpdatedDate: string;
  username: string;
  faceImageUrl: string;
  firstName: string;
  lastName: string;
  position: string;
  currentClubIconUrl: string;
  contractedUntil: string;
  education: string;
  expLevel: string;
  managementStyle: string;
  managementType: string;
  birthDay: string;
  countryFlagUrl: string;
  age: number;
  summary: string;
  topVideoLinks: IVideoLink[] | [];
  specialities: string[];
  starRating: number;
  circleCompleted: number;
  coachRadarSkills: CoachRadarSkillsDto;
  socialLinks: UserSocialLinksDto;
  userRole: UserTypes;
  bioUrl: string;
  teamIds?: string[];
  clubId?: string;
  primaryTeam?: Record<string, any>;
  year: string | number;
  city: string;
  country: string;
  height: number | string;
  weight: number | string;
  currentClub: string;
  currentTeamName: string;
  favoriteRoles?: string[];
  lastMatch?: ILastMatch;
  lastTraining?: ILastTraining;
  clubs?: any[];
}
