export const countries = [
  {
    name: 'Afghanistan',
    alpha2Code: 'AF',
    alpha3Code: 'AFG',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/AFG?alt=media&token=638cbb5f-478b-4adf-8e12-9afe3d089f97',
  },
  {
    name: 'Åland Islands',
    alpha2Code: 'AX',
    alpha3Code: 'ALA',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ALA?alt=media&token=331d44db-fc8e-4f10-ad09-06cb70d51f53',
  },
  {
    name: 'Albania',
    alpha2Code: 'AL',
    alpha3Code: 'ALB',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ALB?alt=media&token=640c24c7-5d7d-420c-b998-dcf240cfb9cb',
  },
  {
    name: 'Algeria',
    alpha2Code: 'DZ',
    alpha3Code: 'DZA',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/DZA?alt=media&token=11fde330-3151-4068-82cb-bb865ad0d433',
  },
  {
    name: 'American Samoa',
    alpha2Code: 'AS',
    alpha3Code: 'ASM',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ASM?alt=media&token=33508775-e40b-4f42-b73f-d7c0615b5902',
  },
  {
    name: 'Andorra',
    alpha2Code: 'AD',
    alpha3Code: 'AND',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/AND?alt=media&token=f4347ba0-53ff-47d6-b8c8-222a18d64da7',
  },
  {
    name: 'Angola',
    alpha2Code: 'AO',
    alpha3Code: 'AGO',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/AGO?alt=media&token=28bd0487-c39f-4469-bd96-62879a893dc1',
  },
  {
    name: 'Anguilla',
    alpha2Code: 'AI',
    alpha3Code: 'AIA',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/AIA?alt=media&token=7dd40194-ec8e-45e6-a40c-4cc257b48371',
  },
  {
    name: 'Antigua and Barbuda',
    alpha2Code: 'AG',
    alpha3Code: 'ATG',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ATG?alt=media&token=8883f7ab-1f9a-479b-83bb-08a8766ed57f',
  },
  {
    name: 'Argentina',
    alpha2Code: 'AR',
    alpha3Code: 'ARG',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ARG?alt=media&token=1bb0aa33-fd80-4468-b1e6-6eb7d567a899',
  },
  {
    name: 'Armenia',
    alpha2Code: 'AM',
    alpha3Code: 'ARM',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ARM?alt=media&token=285f71af-e30e-4a4d-82a9-12e2da65f608',
  },
  {
    name: 'Aruba',
    alpha2Code: 'AW',
    alpha3Code: 'ABW',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ABW?alt=media&token=9dd40c2a-b7ee-4130-bee3-6f825d474605',
  },
  {
    name: 'Australia',
    alpha2Code: 'AU',
    alpha3Code: 'AUS',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/AUS?alt=media&token=7ba5857e-cf06-48b0-ab67-52a55034741f',
  },
  {
    name: 'Austria',
    alpha2Code: 'AT',
    alpha3Code: 'AUT',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/AUT?alt=media&token=3b155f84-4658-47dd-9fc4-6b825050ebf8',
  },
  {
    name: 'Azerbaijan',
    alpha2Code: 'AZ',
    alpha3Code: 'AZE',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/AZE?alt=media&token=8da0ccd9-751d-4b68-87e2-15bcb7532a4f',
  },
  {
    name: 'Bahamas',
    alpha2Code: 'BS',
    alpha3Code: 'BHS',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BHS?alt=media&token=e9583618-2450-4e19-968b-1ed33d7c28a7',
  },
  {
    name: 'Bahrain',
    alpha2Code: 'BH',
    alpha3Code: 'BHR',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BHR?alt=media&token=9ec53c25-f65f-45f0-95ed-62f48dda6fb9',
  },
  {
    name: 'Bangladesh',
    alpha2Code: 'BD',
    alpha3Code: 'BGD',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BGD?alt=media&token=09c32163-8cd9-44b6-a41f-1c51d5e163e9',
  },
  {
    name: 'Barbados',
    alpha2Code: 'BB',
    alpha3Code: 'BRB',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BRB?alt=media&token=17b4bd29-aad2-49dc-b540-d20e04a283f7',
  },
  {
    name: 'Belarus',
    alpha2Code: 'BY',
    alpha3Code: 'BLR',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BLR?alt=media&token=1a01ca11-6df4-479a-802f-7cc203f39b49',
  },
  {
    name: 'Belgium',
    alpha2Code: 'BE',
    alpha3Code: 'BEL',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BEL?alt=media&token=89e8cd70-8712-49f5-942f-e3433381e3d8',
  },
  {
    name: 'Belize',
    alpha2Code: 'BZ',
    alpha3Code: 'BLZ',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BLZ?alt=media&token=4a26e072-46ac-4512-b3fb-8e13e5887c2c',
  },
  {
    name: 'Benin',
    alpha2Code: 'BJ',
    alpha3Code: 'BEN',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BEN?alt=media&token=04cf57b6-8d4e-490f-9dc0-8df605558279',
  },
  {
    name: 'Bermuda',
    alpha2Code: 'BM',
    alpha3Code: 'BMU',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BMU?alt=media&token=03e098b6-abea-45d0-aa41-01065ee55b1a',
  },
  {
    name: 'Bhutan',
    alpha2Code: 'BT',
    alpha3Code: 'BTN',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BTN?alt=media&token=9d8cf157-d0ef-4d42-b9ad-7598ddb3683e',
  },
  {
    name: 'Bolivia (Plurinational State of)',
    alpha2Code: 'BO',
    alpha3Code: 'BOL',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BOL?alt=media&token=aa4d3f0b-1bcd-40fe-86f5-a0f31257460d',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    alpha2Code: 'BQ',
    alpha3Code: 'BES',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BES?alt=media&token=bd21a86d-d4c6-4633-b494-c1ba1b45cbe1',
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2Code: 'BA',
    alpha3Code: 'BIH',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BIH?alt=media&token=d3d95612-6254-4bc0-a42b-458d6dd0c99e',
  },
  {
    name: 'Botswana',
    alpha2Code: 'BW',
    alpha3Code: 'BWA',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BWA?alt=media&token=2ed3cea9-037c-4bac-9990-51b5ddbf8734',
  },
  {
    name: 'Brazil',
    alpha2Code: 'BR',
    alpha3Code: 'BRA',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BRA?alt=media&token=12ddd083-a180-421e-b786-563ad06be411',
  },
  {
    name: 'British Indian Ocean Territory',
    alpha2Code: 'IO',
    alpha3Code: 'IOT',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/IOT?alt=media&token=bc37af13-7f6d-484d-8625-94ae8535ea30',
  },
  {
    name: 'United States Minor Outlying Islands',
    alpha2Code: 'UM',
    alpha3Code: 'UMI',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/UMI?alt=media&token=b8a908b2-bf46-4114-bbeb-b5ecfe1cc09e',
  },
  {
    name: 'Virgin Islands (British)',
    alpha2Code: 'VG',
    alpha3Code: 'VGB',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/VGB?alt=media&token=34ad26ac-af13-4a77-94c7-cfaf816e9803',
  },
  {
    name: 'Virgin Islands (U.S.)',
    alpha2Code: 'VI',
    alpha3Code: 'VIR',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/VIR?alt=media&token=277ba2e5-4442-4a38-9e1e-6f1b8cc27828',
  },
  {
    name: 'Brunei Darussalam',
    alpha2Code: 'BN',
    alpha3Code: 'BRN',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BRN?alt=media&token=a578afef-38f1-4ab3-8bd8-f5d85232ac3c',
  },
  {
    name: 'Bulgaria',
    alpha2Code: 'BG',
    alpha3Code: 'BGR',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BGR?alt=media&token=b9889ab9-a558-4010-91c3-9e406ccad332',
  },
  {
    name: 'Burkina Faso',
    alpha2Code: 'BF',
    alpha3Code: 'BFA',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BFA?alt=media&token=5c89f9c8-0fba-4b9f-9900-a6c82b70f08b',
  },
  {
    name: 'Burundi',
    alpha2Code: 'BI',
    alpha3Code: 'BDI',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BDI?alt=media&token=e0f98a90-d2c1-4302-9fe4-cc6eeb2f7241',
  },
  {
    name: 'Cambodia',
    alpha2Code: 'KH',
    alpha3Code: 'KHM',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/KHM?alt=media&token=4ea938ea-4788-43d2-91dd-b1e27e05f979',
  },
  {
    name: 'Cameroon',
    alpha2Code: 'CM',
    alpha3Code: 'CMR',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CMR?alt=media&token=0b7af0a7-0f80-45e8-b61d-d78dedf305a9',
  },
  {
    name: 'Canada',
    alpha2Code: 'CA',
    alpha3Code: 'CAN',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CAN?alt=media&token=fd64c27d-6e11-4509-9ccf-d2a1799a8faf',
  },
  {
    name: 'Cabo Verde',
    alpha2Code: 'CV',
    alpha3Code: 'CPV',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CPV?alt=media&token=6711c1d1-c3d3-4561-873e-2e88619df0d9',
  },
  {
    name: 'Cayman Islands',
    alpha2Code: 'KY',
    alpha3Code: 'CYM',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CYM?alt=media&token=ef3527ee-dfa6-43c9-a961-7bdd29cd2e1b',
  },
  {
    name: 'Central African Republic',
    alpha2Code: 'CF',
    alpha3Code: 'CAF',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CAF?alt=media&token=0fcbb52a-396c-4c5f-ba49-1489a5eaf9ba',
  },
  {
    name: 'Chad',
    alpha2Code: 'TD',
    alpha3Code: 'TCD',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TCD?alt=media&token=1b603a62-ec50-4fc7-a503-b46e7d8ecad8',
  },
  {
    name: 'Chile',
    alpha2Code: 'CL',
    alpha3Code: 'CHL',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CHL?alt=media&token=a208d41e-fa5c-48bb-bc45-51ead513d5f9',
  },
  {
    name: 'China',
    alpha2Code: 'CN',
    alpha3Code: 'CHN',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CHN?alt=media&token=c6f20361-c7b7-4d4c-8ebb-744b0b6be092',
  },
  {
    name: 'Christmas Island',
    alpha2Code: 'CX',
    alpha3Code: 'CXR',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CXR?alt=media&token=57698576-560f-4ebd-934a-866143c275a8',
  },
  {
    name: 'Cocos (Keeling) Islands',
    alpha2Code: 'CC',
    alpha3Code: 'CCK',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CCK?alt=media&token=9e140abe-327a-4b3b-bf08-1cfd6ca149b6',
  },
  {
    name: 'Colombia',
    alpha2Code: 'CO',
    alpha3Code: 'COL',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/COL?alt=media&token=44bbbf6d-8bf4-4cc2-b4d0-684a4477b26c',
  },
  {
    name: 'Comoros',
    alpha2Code: 'KM',
    alpha3Code: 'COM',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/COM?alt=media&token=fa8e5196-71c8-44e3-86ad-afa0c9df5a73',
  },
  {
    name: 'Congo',
    alpha2Code: 'CG',
    alpha3Code: 'COG',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/COG?alt=media&token=58d7b91e-0c33-4f06-aa81-42e59e3fd1b6',
  },
  {
    name: 'Congo (Democratic Republic of the)',
    alpha2Code: 'CD',
    alpha3Code: 'COD',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/COD?alt=media&token=663a3424-dd5d-45af-8377-bf4efb947d6c',
  },
  {
    name: 'Cook Islands',
    alpha2Code: 'CK',
    alpha3Code: 'COK',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/COK?alt=media&token=a9bb022b-59a1-4e32-abaa-2f6e5aa7d460',
  },
  {
    name: 'Costa Rica',
    alpha2Code: 'CR',
    alpha3Code: 'CRI',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CRI?alt=media&token=f3fa751b-6c33-43ec-b807-6047b17473bf',
  },
  {
    name: 'Croatia',
    alpha2Code: 'HR',
    alpha3Code: 'HRV',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/HRV?alt=media&token=6a8b4158-85e8-4652-8054-88e9a07d6276',
  },
  {
    name: 'Cuba',
    alpha2Code: 'CU',
    alpha3Code: 'CUB',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CUB?alt=media&token=ef61da45-9715-43a5-b6b0-850a1cd54f89',
  },
  {
    name: 'Curaçao',
    alpha2Code: 'CW',
    alpha3Code: 'CUW',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CUW?alt=media&token=dba13023-1ff6-452a-8f28-fc78d2030f63',
  },
  {
    name: 'Cyprus',
    alpha2Code: 'CY',
    alpha3Code: 'CYP',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CYP?alt=media&token=170dc85f-eb78-4bde-93b5-b65658cadd68',
  },
  {
    name: 'Czech Republic',
    alpha2Code: 'CZ',
    alpha3Code: 'CZE',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CZE?alt=media&token=b3557526-6170-4e8a-a99c-963f55d81d43',
  },
  {
    name: 'Denmark',
    alpha2Code: 'DK',
    alpha3Code: 'DNK',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/DNK?alt=media&token=948b2a40-bd76-40d6-ad1b-8e159b279c8f',
  },
  {
    name: 'Djibouti',
    alpha2Code: 'DJ',
    alpha3Code: 'DJI',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/DJI?alt=media&token=3e0ba167-da97-4694-b807-00a0254864ae',
  },
  {
    name: 'Dominica',
    alpha2Code: 'DM',
    alpha3Code: 'DMA',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/DMA?alt=media&token=1d588ab8-01bd-4639-aacf-a1b9d591d546',
  },
  {
    name: 'Dominican Republic',
    alpha2Code: 'DO',
    alpha3Code: 'DOM',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/DOM?alt=media&token=3acbb3d8-c0dc-4a93-ab45-ed76260b5899',
  },
  {
    name: 'Ecuador',
    alpha2Code: 'EC',
    alpha3Code: 'ECU',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ECU?alt=media&token=68cd8ec3-e81a-4370-ba80-8452fe915d63',
  },
  {
    name: 'Egypt',
    alpha2Code: 'EG',
    alpha3Code: 'EGY',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/EGY?alt=media&token=6c8f979a-34d1-4507-8ad0-7b0a1876ad95',
  },
  {
    name: 'El Salvador',
    alpha2Code: 'SV',
    alpha3Code: 'SLV',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SLV?alt=media&token=43dddbfb-0c63-41ef-8398-f1345ef34c2c',
  },
  {
    name: 'England',
    alpha2Code: 'EN',
    alpha3Code: 'ENG',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ENG?alt=media&token=badf4838-9e99-445a-af0b-fb8a31ec6d52',
  },
  {
    name: 'Equatorial Guinea',
    alpha2Code: 'GQ',
    alpha3Code: 'GNQ',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GNQ?alt=media&token=731b1140-612d-4ef7-8ea6-8ca416df75e5',
  },
  {
    name: 'Eritrea',
    alpha2Code: 'ER',
    alpha3Code: 'ERI',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ERI?alt=media&token=bb0c1d46-9ceb-406a-a7fe-67f18b9e9d40',
  },
  {
    name: 'Estonia',
    alpha2Code: 'EE',
    alpha3Code: 'EST',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/EST?alt=media&token=21dc99e5-9279-4663-9cd7-25974926f4e9',
  },
  {
    name: 'Ethiopia',
    alpha2Code: 'ET',
    alpha3Code: 'ETH',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ETH?alt=media&token=29de2b85-f37b-4a3b-b660-f2de1068d93c',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    alpha2Code: 'FK',
    alpha3Code: 'FLK',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/FLK?alt=media&token=3b878aaa-ab84-4f21-8e76-0c1701dd1fdc',
  },
  {
    name: 'Faroe Islands',
    alpha2Code: 'FO',
    alpha3Code: 'FRO',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/FRO?alt=media&token=b59cba87-25a7-4e76-825b-5155b15b78c4',
  },
  {
    name: 'Fiji',
    alpha2Code: 'FJ',
    alpha3Code: 'FJI',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/FJI?alt=media&token=1be2bf36-c56d-4d95-b134-e9e3fb851916',
  },
  {
    name: 'Finland',
    alpha2Code: 'FI',
    alpha3Code: 'FIN',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/FIN?alt=media&token=ec3c77fc-75a5-48ff-9d1d-c8c5ec71a7c6',
  },
  {
    name: 'France',
    alpha2Code: 'FR',
    alpha3Code: 'FRA',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/FRA?alt=media&token=f1d1fb3a-2a1b-4dfa-b829-c9251146a049',
  },
  {
    name: 'French Guiana',
    alpha2Code: 'GF',
    alpha3Code: 'GUF',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GUF?alt=media&token=422c2386-2ee3-476c-8bdc-9f7b42bd464a',
  },
  {
    name: 'French Polynesia',
    alpha2Code: 'PF',
    alpha3Code: 'PYF',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PYF?alt=media&token=bdc5f9b8-787a-4932-be7f-4670f5732d7e',
  },
  {
    name: 'French Southern Territories',
    alpha2Code: 'TF',
    alpha3Code: 'ATF',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ATF?alt=media&token=7981b245-8ed2-4f9e-9338-0f6f973aa9dc',
  },
  {
    name: 'Gabon',
    alpha2Code: 'GA',
    alpha3Code: 'GAB',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GAB?alt=media&token=40c152e9-dd72-4c3c-b3bb-9034b8c9bc7c',
  },
  {
    name: 'Gambia',
    alpha2Code: 'GM',
    alpha3Code: 'GMB',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GMB?alt=media&token=2f8c6483-2500-4da7-82c6-fee0b7833302',
  },
  {
    name: 'Georgia',
    alpha2Code: 'GE',
    alpha3Code: 'GEO',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GEO?alt=media&token=9982238f-71fb-4440-a0ff-c44531cd4961',
  },
  {
    name: 'Germany',
    alpha2Code: 'DE',
    alpha3Code: 'DEU',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/DEU?alt=media&token=e8293e8c-3533-451a-b11e-f89d1c30fe83',
  },
  {
    name: 'Ghana',
    alpha2Code: 'GH',
    alpha3Code: 'GHA',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GHA?alt=media&token=3940f972-2b6e-4ae2-a6d1-cb2c5b27137e',
  },
  {
    name: 'Gibraltar',
    alpha2Code: 'GI',
    alpha3Code: 'GIB',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GIB?alt=media&token=ad2577f0-c132-4fab-96e9-1fa10a77d722',
  },
  {
    name: 'Greece',
    alpha2Code: 'GR',
    alpha3Code: 'GRC',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GRC?alt=media&token=9cf6b650-0eec-448a-bc61-6bf92916d01a',
  },
  {
    name: 'Greenland',
    alpha2Code: 'GL',
    alpha3Code: 'GRL',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GRL?alt=media&token=aba64a9d-dbae-4e82-b8fe-118c0467991e',
  },
  {
    name: 'Grenada',
    alpha2Code: 'GD',
    alpha3Code: 'GRD',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GRD?alt=media&token=baffe103-4cca-4bfb-baec-cd62b862768e',
  },
  {
    name: 'Guadeloupe',
    alpha2Code: 'GP',
    alpha3Code: 'GLP',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GLP?alt=media&token=2d633af2-298a-4f83-9e15-42f16e334b63',
  },
  {
    name: 'Guam',
    alpha2Code: 'GU',
    alpha3Code: 'GUM',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GUM?alt=media&token=c979e2a9-fb47-47a9-8d12-e08d7215c573',
  },
  {
    name: 'Guatemala',
    alpha2Code: 'GT',
    alpha3Code: 'GTM',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GTM?alt=media&token=67b349fa-5b88-4318-88d2-7ced29c2fade',
  },
  {
    name: 'Guernsey',
    alpha2Code: 'GG',
    alpha3Code: 'GGY',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GGY?alt=media&token=f09015db-929a-425e-b1f3-b791986b9394',
  },
  {
    name: 'Guinea',
    alpha2Code: 'GN',
    alpha3Code: 'GIN',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GIN?alt=media&token=9db52ed7-77f6-4e1f-ad37-4aec0109d59d',
  },
  {
    name: 'Guinea-Bissau',
    alpha2Code: 'GW',
    alpha3Code: 'GNB',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GNB?alt=media&token=c0270b09-3311-464e-824e-2a64fac5d11b',
  },
  {
    name: 'Guyana',
    alpha2Code: 'GY',
    alpha3Code: 'GUY',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GUY?alt=media&token=8b00d682-8c02-4b27-9a01-d5c9bc09e436',
  },
  {
    name: 'Haiti',
    alpha2Code: 'HT',
    alpha3Code: 'HTI',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/HTI?alt=media&token=01ea44af-e9c7-4f4c-b821-5a1a1a4125c3',
  },
  {
    name: 'Holy See',
    alpha2Code: 'VA',
    alpha3Code: 'VAT',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/VAT?alt=media&token=3f3f47c2-bac3-4477-8abf-d64e25cc8479',
  },
  {
    name: 'Honduras',
    alpha2Code: 'HN',
    alpha3Code: 'HND',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/HND?alt=media&token=0df60ee2-f0d8-4e15-b14d-e9e75fbe4aff',
  },
  {
    name: 'Hong Kong',
    alpha2Code: 'HK',
    alpha3Code: 'HKG',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/HKG?alt=media&token=c55be9d1-9c10-4a18-b2f2-bbc8aef1aaca',
  },
  {
    name: 'Hungary',
    alpha2Code: 'HU',
    alpha3Code: 'HUN',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/HUN?alt=media&token=2c1b4954-b988-42e8-bc51-afd8021cbf58',
  },
  {
    name: 'Iceland',
    alpha2Code: 'IS',
    alpha3Code: 'ISL',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ISL?alt=media&token=50141580-d980-4cd6-98b5-fe5d2830d6f1',
  },
  {
    name: 'India',
    alpha2Code: 'IN',
    alpha3Code: 'IND',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/IND?alt=media&token=8b8f0e28-b8a6-438f-99f9-144c61fdf302',
  },
  {
    name: 'Indonesia',
    alpha2Code: 'ID',
    alpha3Code: 'IDN',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/IDN?alt=media&token=c54a7319-1927-49b4-96f5-79826426efae',
  },
  {
    name: "Côte d'Ivoire",
    alpha2Code: 'CI',
    alpha3Code: 'CIV',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CIV?alt=media&token=f7b8c535-ae4b-478a-8829-7ae9ac798e7b',
  },
  {
    name: 'Iran (Islamic Republic of)',
    alpha2Code: 'IR',
    alpha3Code: 'IRN',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/IRN?alt=media&token=dffd82bf-07c2-423c-b051-5846133d34ab',
  },
  {
    name: 'Iraq',
    alpha2Code: 'IQ',
    alpha3Code: 'IRQ',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/IRQ?alt=media&token=cd6a8d79-4ec5-4acf-a37f-ab9c4cdc87e7',
  },
  {
    name: 'Ireland',
    alpha2Code: 'IE',
    alpha3Code: 'IRL',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/IRL?alt=media&token=765fc325-6726-4d21-b568-663aa2c1eccd',
  },
  {
    name: 'Isle of Man',
    alpha2Code: 'IM',
    alpha3Code: 'IMN',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/IMN?alt=media&token=64321643-7a8a-4040-9090-6c5b86d05beb',
  },
  {
    name: 'Israel',
    alpha2Code: 'IL',
    alpha3Code: 'ISR',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ISR?alt=media&token=f4daebd0-f862-494a-bc37-01cc79fede84',
  },
  {
    name: 'Italy',
    alpha2Code: 'IT',
    alpha3Code: 'ITA',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ITA?alt=media&token=e14e9d7b-6b94-4e29-9836-c23248f45a97',
  },
  {
    name: 'Jamaica',
    alpha2Code: 'JM',
    alpha3Code: 'JAM',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/JAM?alt=media&token=b14a8cdc-08f1-4d4c-a7e1-28b400d4e971',
  },
  {
    name: 'Japan',
    alpha2Code: 'JP',
    alpha3Code: 'JPN',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/JPN?alt=media&token=ca0827db-8618-436a-ab6b-3bbac83041f0',
  },
  {
    name: 'Jersey',
    alpha2Code: 'JE',
    alpha3Code: 'JEY',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/JEY?alt=media&token=68467632-cc0d-4824-b49d-e0f4720b888c',
  },
  {
    name: 'Jordan',
    alpha2Code: 'JO',
    alpha3Code: 'JOR',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/JOR?alt=media&token=d1e32424-37fa-40b9-9175-9bffff792771',
  },
  {
    name: 'Kazakhstan',
    alpha2Code: 'KZ',
    alpha3Code: 'KAZ',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/KAZ?alt=media&token=94858b25-f08f-4dc0-8d7f-fbd49432c8f1',
  },
  {
    name: 'Kenya',
    alpha2Code: 'KE',
    alpha3Code: 'KEN',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/KEN?alt=media&token=f5fe2f45-f972-4a6f-8283-3df0f6b56f23',
  },
  {
    name: 'Kiribati',
    alpha2Code: 'KI',
    alpha3Code: 'KIR',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/KIR?alt=media&token=a575cee8-b4ac-4d8b-aead-8e047e15458c',
  },
  {
    name: 'Kuwait',
    alpha2Code: 'KW',
    alpha3Code: 'KWT',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/KWT?alt=media&token=a5e0c24f-28fe-48a6-9ebe-7e87f08ef96d',
  },
  {
    name: 'Kyrgyzstan',
    alpha2Code: 'KG',
    alpha3Code: 'KGZ',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/KGZ?alt=media&token=f33d5bc3-1108-4c79-95c5-f71ebb3f107c',
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2Code: 'LA',
    alpha3Code: 'LAO',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/LAO?alt=media&token=a7c41216-c26b-47c6-966a-36f9569f50fc',
  },
  {
    name: 'Latvia',
    alpha2Code: 'LV',
    alpha3Code: 'LVA',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/LVA?alt=media&token=e4e1f774-7f20-42b7-a675-8ea26cea8232',
  },
  {
    name: 'Lebanon',
    alpha2Code: 'LB',
    alpha3Code: 'LBN',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/LBN?alt=media&token=430c8edb-a973-4e0a-ba15-2fbf11caafe1',
  },
  {
    name: 'Lesotho',
    alpha2Code: 'LS',
    alpha3Code: 'LSO',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/LSO?alt=media&token=99ede59a-f490-49e0-ae6f-4b98f8aa2599',
  },
  {
    name: 'Liberia',
    alpha2Code: 'LR',
    alpha3Code: 'LBR',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/LBR?alt=media&token=cce85c62-601b-4b93-a21d-5c11d1295819',
  },
  {
    name: 'Libya',
    alpha2Code: 'LY',
    alpha3Code: 'LBY',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/LBY?alt=media&token=f93d418f-4601-4c09-95d0-031808579b6d',
  },
  {
    name: 'Liechtenstein',
    alpha2Code: 'LI',
    alpha3Code: 'LIE',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/LIE?alt=media&token=a008bd88-f58e-40d2-a1fc-dd306d41dfc4',
  },
  {
    name: 'Lithuania',
    alpha2Code: 'LT',
    alpha3Code: 'LTU',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/LTU?alt=media&token=d6ebbb91-f132-4ec7-acba-3144eef3f841',
  },
  {
    name: 'Luxembourg',
    alpha2Code: 'LU',
    alpha3Code: 'LUX',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/LUX?alt=media&token=1d05bb14-5d78-4b1c-b836-e9ab0f196f18',
  },
  {
    name: 'Macao',
    alpha2Code: 'MO',
    alpha3Code: 'MAC',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MAC?alt=media&token=76a5097b-6838-4f7d-9c11-59b2266b5cd4',
  },
  {
    name: 'Macedonia (the former Yugoslav Republic of)',
    alpha2Code: 'MK',
    alpha3Code: 'MKD',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MKD?alt=media&token=04885908-1c31-41a4-8df4-594175bee27c',
  },
  {
    name: 'Madagascar',
    alpha2Code: 'MG',
    alpha3Code: 'MDG',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MDG?alt=media&token=292b0a6d-5763-4d5d-bde7-127c051f6d73',
  },
  {
    name: 'Malawi',
    alpha2Code: 'MW',
    alpha3Code: 'MWI',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MWI?alt=media&token=292dea08-ec7e-4ad9-ac41-2499e17915da',
  },
  {
    name: 'Malaysia',
    alpha2Code: 'MY',
    alpha3Code: 'MYS',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MYS?alt=media&token=d6b4372b-f58d-4ad4-ae56-0990b1a2d9fc',
  },
  {
    name: 'Maldives',
    alpha2Code: 'MV',
    alpha3Code: 'MDV',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MDV?alt=media&token=26c65711-bd47-41eb-92b7-110ed94563f3',
  },
  {
    name: 'Mali',
    alpha2Code: 'ML',
    alpha3Code: 'MLI',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MLI?alt=media&token=450b92a7-d8b7-4b09-bb51-4c93f5de3941',
  },
  {
    name: 'Malta',
    alpha2Code: 'MT',
    alpha3Code: 'MLT',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MLT?alt=media&token=24e2072a-2f82-4f4b-8eed-81449373e095',
  },
  {
    name: 'Marshall Islands',
    alpha2Code: 'MH',
    alpha3Code: 'MHL',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MHL?alt=media&token=df6e3034-8202-4e86-82bf-67b221bd6db6',
  },
  {
    name: 'Martinique',
    alpha2Code: 'MQ',
    alpha3Code: 'MTQ',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MTQ?alt=media&token=69b65836-bdf5-4f52-9f4b-e00cb658d98e',
  },
  {
    name: 'Mauritania',
    alpha2Code: 'MR',
    alpha3Code: 'MRT',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MRT?alt=media&token=c7549c12-c4c2-4373-acf5-1f290a6b550a',
  },
  {
    name: 'Mauritius',
    alpha2Code: 'MU',
    alpha3Code: 'MUS',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MUS?alt=media&token=fb615ae3-4a3d-4904-87cf-ecef85e0e3a1',
  },
  {
    name: 'Mayotte',
    alpha2Code: 'YT',
    alpha3Code: 'MYT',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MYT?alt=media&token=cd0a5467-3be9-430a-a32f-dd460bd5e63b',
  },
  {
    name: 'Mexico',
    alpha2Code: 'MX',
    alpha3Code: 'MEX',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MEX?alt=media&token=65daf19e-caf7-414b-b005-f384bce8873b',
  },
  {
    name: 'Micronesia (Federated States of)',
    alpha2Code: 'FM',
    alpha3Code: 'FSM',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/FSM?alt=media&token=bbf63b49-4ee1-45d0-a2f0-021ec391cda3',
  },
  {
    name: 'Moldova (Republic of)',
    alpha2Code: 'MD',
    alpha3Code: 'MDA',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MDA?alt=media&token=fe9ecaf3-572c-43b1-837b-929954471429',
  },
  {
    name: 'Monaco',
    alpha2Code: 'MC',
    alpha3Code: 'MCO',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MCO?alt=media&token=aa343d1d-41b4-4d92-ac00-391111027ad7',
  },
  {
    name: 'Mongolia',
    alpha2Code: 'MN',
    alpha3Code: 'MNG',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MNG?alt=media&token=461c6149-8de2-4084-bc4a-60a177e6786c',
  },
  {
    name: 'Montenegro',
    alpha2Code: 'ME',
    alpha3Code: 'MNE',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MNE?alt=media&token=5a73fa72-853d-404f-8987-bda15801304e',
  },
  {
    name: 'Montserrat',
    alpha2Code: 'MS',
    alpha3Code: 'MSR',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MSR?alt=media&token=2dda0932-4439-4db6-87b6-c1eb0a45fd54',
  },
  {
    name: 'Morocco',
    alpha2Code: 'MA',
    alpha3Code: 'MAR',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MAR?alt=media&token=688e6c0a-2885-4985-9a3a-3817033e1d49',
  },
  {
    name: 'Mozambique',
    alpha2Code: 'MZ',
    alpha3Code: 'MOZ',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MOZ?alt=media&token=fef57275-004e-4fe8-a446-510212029399',
  },
  {
    name: 'Myanmar',
    alpha2Code: 'MM',
    alpha3Code: 'MMR',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MMR?alt=media&token=906df41c-aefa-4b62-8939-768ccc73ca84',
  },
  {
    name: 'Namibia',
    alpha2Code: 'NA',
    alpha3Code: 'NAM',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/NAM?alt=media&token=8491fc37-cbf2-4ed0-9018-0a3d35edac2d',
  },
  {
    name: 'Nauru',
    alpha2Code: 'NR',
    alpha3Code: 'NRU',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/NRU?alt=media&token=4f71e7b3-b738-4d0f-b288-3eb47b133b83',
  },
  {
    name: 'Nepal',
    alpha2Code: 'NP',
    alpha3Code: 'NPL',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/NPL?alt=media&token=1ec44b9a-6bc7-4e67-acdd-89738ed3457f',
  },
  {
    name: 'Netherlands',
    alpha2Code: 'NL',
    alpha3Code: 'NLD',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/NLD?alt=media&token=58d346fe-0575-4edb-8431-24d1664f718d',
  },
  {
    name: 'New Caledonia',
    alpha2Code: 'NC',
    alpha3Code: 'NCL',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/NCL?alt=media&token=3462817f-826d-4fea-b136-9dbdc3f19bad',
  },
  {
    name: 'New Zealand',
    alpha2Code: 'NZ',
    alpha3Code: 'NZL',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/NZL?alt=media&token=b32bb5eb-26bb-44e4-9ea2-1868db4c76d9',
  },
  {
    name: 'Nicaragua',
    alpha2Code: 'NI',
    alpha3Code: 'NIC',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/NIC?alt=media&token=42a66d66-91c9-40a6-aeca-4320e51cbf6b',
  },
  {
    name: 'Niger',
    alpha2Code: 'NE',
    alpha3Code: 'NER',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/NER?alt=media&token=42acd9ea-5b5c-46dc-9559-3f8c2d7af008',
  },
  {
    name: 'Nigeria',
    alpha2Code: 'NG',
    alpha3Code: 'NGA',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/NGA?alt=media&token=b244db2b-dfae-44e3-aa94-05e1a28c78a1',
  },
  {
    name: 'Niue',
    alpha2Code: 'NU',
    alpha3Code: 'NIU',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/NIU?alt=media&token=7ba6cc79-5d9b-4565-a43d-f8bf83d9c92b',
  },
  {
    name: 'Norfolk Island',
    alpha2Code: 'NF',
    alpha3Code: 'NFK',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/NFK?alt=media&token=113cfe6f-240a-4b4e-b11c-891c7ed18e5c',
  },
  {
    name: "Korea (Democratic People's Republic of)",
    alpha2Code: 'KP',
    alpha3Code: 'PRK',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PRK?alt=media&token=f51337a0-4205-461e-9a76-0f13d822a4c8',
  },
  {
    name: 'Northern Mariana Islands',
    alpha2Code: 'MP',
    alpha3Code: 'MNP',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MNP?alt=media&token=ae048f7b-4703-44ad-b250-678ecd622a9b',
  },
  {
    name: 'Norway',
    alpha2Code: 'NO',
    alpha3Code: 'NOR',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/NOR?alt=media&token=76a40dde-0d5b-406f-b228-7cb0ba2b8e6a',
  },
  {
    name: 'Oman',
    alpha2Code: 'OM',
    alpha3Code: 'OMN',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/OMN?alt=media&token=12903c68-f5a4-406c-b1f9-e3947aae88dd',
  },
  {
    name: 'Pakistan',
    alpha2Code: 'PK',
    alpha3Code: 'PAK',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PAK?alt=media&token=079cca39-6c38-4f16-817a-7ff2b7594524',
  },
  {
    name: 'Palau',
    alpha2Code: 'PW',
    alpha3Code: 'PLW',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PLW?alt=media&token=d899e088-fdab-423f-be7e-863b2ed19983',
  },
  {
    name: 'Palestine, State of',
    alpha2Code: 'PS',
    alpha3Code: 'PSE',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PSE?alt=media&token=fcba42cb-b877-4301-a17b-409ad4ac59c7',
  },
  {
    name: 'Panama',
    alpha2Code: 'PA',
    alpha3Code: 'PAN',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PAN?alt=media&token=6632d297-b731-414a-918f-e89a535e7640',
  },
  {
    name: 'Papua New Guinea',
    alpha2Code: 'PG',
    alpha3Code: 'PNG',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PNG?alt=media&token=db8f2794-1d17-47d4-be4d-98784749cc11',
  },
  {
    name: 'Paraguay',
    alpha2Code: 'PY',
    alpha3Code: 'PRY',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PRY?alt=media&token=04153459-839b-49b5-b2cd-6b8245e52b0b',
  },
  {
    name: 'Peru',
    alpha2Code: 'PE',
    alpha3Code: 'PER',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PER?alt=media&token=93a0229e-4dad-4538-9752-39b7091bb1d6',
  },
  {
    name: 'Philippines',
    alpha2Code: 'PH',
    alpha3Code: 'PHL',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PHL?alt=media&token=74124ab5-9ede-4bd7-b3e1-4643a43fa8a5',
  },
  {
    name: 'Pitcairn',
    alpha2Code: 'PN',
    alpha3Code: 'PCN',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PCN?alt=media&token=bbe2df1e-33a5-4a70-b522-6c0583b45683',
  },
  {
    name: 'Poland',
    alpha2Code: 'PL',
    alpha3Code: 'POL',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/POL?alt=media&token=94ca9852-c4e6-46ba-89e0-c04673d26688',
  },
  {
    name: 'Portugal',
    alpha2Code: 'PT',
    alpha3Code: 'PRT',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PRT?alt=media&token=3d197081-6fd0-4bb4-abcf-d52b3b0e5e96',
  },
  {
    name: 'Puerto Rico',
    alpha2Code: 'PR',
    alpha3Code: 'PRI',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/PRI?alt=media&token=b607267c-7468-4bee-b3bb-3bb3537faf24',
  },
  {
    name: 'Qatar',
    alpha2Code: 'QA',
    alpha3Code: 'QAT',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/QAT?alt=media&token=82983518-7462-473d-8ac7-b7dfbef07580',
  },
  {
    name: 'Republic of Kosovo',
    alpha2Code: 'XK',
    alpha3Code: 'KOS',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/KOS?alt=media&token=dd0ef3d3-8719-480b-994c-ada907e3b959',
  },
  {
    name: 'Réunion',
    alpha2Code: 'RE',
    alpha3Code: 'REU',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/REU?alt=media&token=78ad7ba2-0bd7-48e0-8836-08c566e53e71',
  },
  {
    name: 'Romania',
    alpha2Code: 'RO',
    alpha3Code: 'ROU',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ROU?alt=media&token=702548b6-0fec-4563-88d0-e2e772e86819',
  },
  {
    name: 'Russian Federation',
    alpha2Code: 'RU',
    alpha3Code: 'RUS',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/RUS?alt=media&token=3859d34f-122b-4d00-b137-4d676eff3c2b',
  },
  {
    name: 'Rwanda',
    alpha2Code: 'RW',
    alpha3Code: 'RWA',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/RWA?alt=media&token=1770a516-9890-4e0b-a470-3bc9883f8a81',
  },
  {
    name: 'Saint Barthélemy',
    alpha2Code: 'BL',
    alpha3Code: 'BLM',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BLM?alt=media&token=0001f2d5-3690-41a3-99c8-b5410cca95b2',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    alpha2Code: 'SH',
    alpha3Code: 'SHN',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SHN?alt=media&token=afbb2f08-63db-49ec-8d45-f5e555c2fec3',
  },
  {
    name: 'Saint Kitts and Nevis',
    alpha2Code: 'KN',
    alpha3Code: 'KNA',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/KNA?alt=media&token=8396e0b9-1eb2-41ea-8f10-b3945913a7f0',
  },
  {
    name: 'Saint Lucia',
    alpha2Code: 'LC',
    alpha3Code: 'LCA',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/LCA?alt=media&token=5150b02b-cffd-44d2-8bee-c37d8d8cd090',
  },
  {
    name: 'Saint Martin (French part)',
    alpha2Code: 'MF',
    alpha3Code: 'MAF',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/MAF?alt=media&token=32166b4e-01b1-4a19-a18d-8b43862dd33b',
  },
  {
    name: 'Saint Pierre and Miquelon',
    alpha2Code: 'PM',
    alpha3Code: 'SPM',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SPM?alt=media&token=94cb6e24-5bd0-4452-837b-be390157eca2',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    alpha2Code: 'VC',
    alpha3Code: 'VCT',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/VCT?alt=media&token=08c0d5d2-4719-4ef9-92ff-4d1e53e09a8a',
  },
  {
    name: 'Samoa',
    alpha2Code: 'WS',
    alpha3Code: 'WSM',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/WSM?alt=media&token=66c7bbff-5117-4945-aa29-38091ebdeeab',
  },
  {
    name: 'San Marino',
    alpha2Code: 'SM',
    alpha3Code: 'SMR',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SMR?alt=media&token=1acaf1e0-27d9-42b2-a017-e5f83d6a6558',
  },
  {
    name: 'Sao Tome and Principe',
    alpha2Code: 'ST',
    alpha3Code: 'STP',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/STP?alt=media&token=20f7af53-0373-4c79-a7bc-01e3529e5450',
  },
  {
    name: 'Saudi Arabia',
    alpha2Code: 'SA',
    alpha3Code: 'SAU',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SAU?alt=media&token=00bf33ef-5335-43d0-8d39-7719f01a9fab',
  },
  {
    name: 'Senegal',
    alpha2Code: 'SN',
    alpha3Code: 'SEN',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SEN?alt=media&token=edf6349f-88a8-4b5b-93aa-bcfb2210526c',
  },
  {
    name: 'Serbia',
    alpha2Code: 'RS',
    alpha3Code: 'SRB',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SRB?alt=media&token=c407c8ac-68e8-4e92-a33d-4359d79d4fa5',
  },
  {
    name: 'Seychelles',
    alpha2Code: 'SC',
    alpha3Code: 'SYC',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SYC?alt=media&token=5eded433-5872-4132-81b1-48c1f71a1203',
  },
  {
    name: 'Sierra Leone',
    alpha2Code: 'SL',
    alpha3Code: 'SLE',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SLE?alt=media&token=9d7a58f8-6ca3-45b5-b5c5-26c160d57fea',
  },
  {
    name: 'Singapore',
    alpha2Code: 'SG',
    alpha3Code: 'SGP',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SGP?alt=media&token=987c7d47-d0b6-46f2-a6cf-c7e5eadcd919',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    alpha2Code: 'SX',
    alpha3Code: 'SXM',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SXM?alt=media&token=1e100432-ea0e-4551-9319-e7065dc66f93',
  },
  {
    name: 'Slovakia',
    alpha2Code: 'SK',
    alpha3Code: 'SVK',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SVK?alt=media&token=2a32fa67-c683-4006-8946-d1761728933b',
  },
  {
    name: 'Slovenia',
    alpha2Code: 'SI',
    alpha3Code: 'SVN',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SVN?alt=media&token=7722be1b-8a36-4eac-b82a-75fb82418078',
  },
  {
    name: 'Solomon Islands',
    alpha2Code: 'SB',
    alpha3Code: 'SLB',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SLB?alt=media&token=668fe087-b193-44cd-a825-82f0f993ef75',
  },
  {
    name: 'Somalia',
    alpha2Code: 'SO',
    alpha3Code: 'SOM',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SOM?alt=media&token=8479131e-958e-466b-afa1-7d05d5fd374a',
  },
  {
    name: 'South Africa',
    alpha2Code: 'ZA',
    alpha3Code: 'ZAF',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ZAF?alt=media&token=cc677537-128c-46dc-bc73-4d3d720340e3',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    alpha2Code: 'GS',
    alpha3Code: 'SGS',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SGS?alt=media&token=495cdb29-5699-4577-8239-5701a08e9068',
  },
  {
    name: 'Korea (Republic of)',
    alpha2Code: 'KR',
    alpha3Code: 'KOR',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/KOR?alt=media&token=5f79b3ae-1175-4c70-9b81-0e2249d73772',
  },
  {
    name: 'South Sudan',
    alpha2Code: 'SS',
    alpha3Code: 'SSD',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SSD?alt=media&token=8f37cc52-0051-4c6c-8500-fca33bfc1bf1',
  },
  {
    name: 'Spain',
    alpha2Code: 'ES',
    alpha3Code: 'ESP',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ESP?alt=media&token=fc57d2a0-e40a-40fa-ae49-8fda60099691',
  },
  {
    name: 'Sri Lanka',
    alpha2Code: 'LK',
    alpha3Code: 'LKA',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/LKA?alt=media&token=587e4161-810f-4956-aab1-0f0f61b1896a',
  },
  {
    name: 'Sudan',
    alpha2Code: 'SD',
    alpha3Code: 'SDN',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SDN?alt=media&token=1f80802a-8268-4928-bb29-70d8ab52630e',
  },
  {
    name: 'Suriname',
    alpha2Code: 'SR',
    alpha3Code: 'SUR',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SUR?alt=media&token=2121423d-1c48-4d23-8a9f-3841e115d10d',
  },
  {
    name: 'Svalbard and Jan Mayen',
    alpha2Code: 'SJ',
    alpha3Code: 'SJM',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SJM?alt=media&token=f53e1d1d-0204-485e-99eb-be49b734421a',
  },
  {
    name: 'Swaziland',
    alpha2Code: 'SZ',
    alpha3Code: 'SWZ',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SWZ?alt=media&token=173e1b5b-52a1-447e-abe4-63292361b507',
  },
  {
    name: 'Sweden',
    alpha2Code: 'SE',
    alpha3Code: 'SWE',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SWE?alt=media&token=585b8f9f-7e55-40b6-8c68-1d479428532d',
  },
  {
    name: 'Switzerland',
    alpha2Code: 'CH',
    alpha3Code: 'CHE',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/CHE?alt=media&token=e19ba23c-9eb6-4a5a-884e-e961fc1144e2',
  },
  {
    name: 'Syrian Arab Republic',
    alpha2Code: 'SY',
    alpha3Code: 'SYR',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SYR?alt=media&token=79856a20-310e-4ff1-ad6c-852f3e8a7b85',
  },
  {
    name: 'Taiwan',
    alpha2Code: 'TW',
    alpha3Code: 'TWN',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TWN?alt=media&token=35802f7e-aabb-47b2-bccd-b82aac586cf0',
  },
  {
    name: 'Tajikistan',
    alpha2Code: 'TJ',
    alpha3Code: 'TJK',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TJK?alt=media&token=aa5daa4e-9f87-412e-a1e1-b5f2f81c2cdb',
  },
  {
    name: 'Tanzania, United Republic of',
    alpha2Code: 'TZ',
    alpha3Code: 'TZA',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TZA?alt=media&token=a918b6dc-f4dd-4896-ab0a-db211c436b6b',
  },
  {
    name: 'Thailand',
    alpha2Code: 'TH',
    alpha3Code: 'THA',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/THA?alt=media&token=32340d37-d1ec-4925-bd59-016bd40205d2',
  },
  {
    name: 'Timor-Leste',
    alpha2Code: 'TL',
    alpha3Code: 'TLS',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TLS?alt=media&token=12129872-bef0-47e6-a3c7-1f18f95d894f',
  },
  {
    name: 'Togo',
    alpha2Code: 'TG',
    alpha3Code: 'TGO',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TGO?alt=media&token=b2863953-5ea7-4589-a170-ef8494cd3269',
  },
  {
    name: 'Tokelau',
    alpha2Code: 'TK',
    alpha3Code: 'TKL',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TKL?alt=media&token=e72b054c-8154-4a58-9f58-e4c2f99ff4dc',
  },
  {
    name: 'Tonga',
    alpha2Code: 'TO',
    alpha3Code: 'TON',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TON?alt=media&token=d5123044-eabe-446c-bb71-652dfb895c32',
  },
  {
    name: 'Trinidad and Tobago',
    alpha2Code: 'TT',
    alpha3Code: 'TTO',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TTO?alt=media&token=8904306a-e54a-4eed-9d18-ad27279a0917',
  },
  {
    name: 'Tunisia',
    alpha2Code: 'TN',
    alpha3Code: 'TUN',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TUN?alt=media&token=08fc8b3d-e8f3-4ca4-95b7-e7ca42e46df6',
  },
  {
    name: 'Turkey',
    alpha2Code: 'TR',
    alpha3Code: 'TUR',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TUR?alt=media&token=59887c48-614c-42b0-8e29-3f3eb91ce36f',
  },
  {
    name: 'Turkmenistan',
    alpha2Code: 'TM',
    alpha3Code: 'TKM',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TKM?alt=media&token=6ebba574-7350-4f12-915e-4344fd67273b',
  },
  {
    name: 'Turks and Caicos Islands',
    alpha2Code: 'TC',
    alpha3Code: 'TCA',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TCA?alt=media&token=a3a68725-7601-4988-813a-f6610d0907df',
  },
  {
    name: 'Tuvalu',
    alpha2Code: 'TV',
    alpha3Code: 'TUV',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/TUV?alt=media&token=3f66c631-c5e8-4826-8d7d-b65108d5f7ed',
  },
  {
    name: 'Uganda',
    alpha2Code: 'UG',
    alpha3Code: 'UGA',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/UGA?alt=media&token=11aacaeb-c655-4562-b132-d50e35e7c4a5',
  },
  {
    name: 'Ukraine',
    alpha2Code: 'UA',
    alpha3Code: 'UKR',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/UKR?alt=media&token=ca762ce0-0f50-46b7-bfb1-914e937c2d87',
  },
  {
    name: 'United Arab Emirates',
    alpha2Code: 'AE',
    alpha3Code: 'ARE',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ARE?alt=media&token=20604805-23e0-440e-a8b5-eff626a57751',
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    alpha2Code: 'GB',
    alpha3Code: 'GBR',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/GBR?alt=media&token=5e88412c-2bc3-4c75-b00d-8f740dc2cacc',
  },
  {
    name: 'United States of America',
    alpha2Code: 'US',
    alpha3Code: 'USA',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/USA?alt=media&token=e2ce3239-0306-40a8-9472-754fa9840ba0',
  },
  {
    name: 'Uruguay',
    alpha2Code: 'UY',
    alpha3Code: 'URY',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/URY?alt=media&token=68754e53-4f35-4758-a5cf-b0e20c318213',
  },
  {
    name: 'Uzbekistan',
    alpha2Code: 'UZ',
    alpha3Code: 'UZB',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/UZB?alt=media&token=928ca6cf-38c4-4f58-92e7-a76f5f634255',
  },
  {
    name: 'Scotland',
    alpha3Code: 'SCT',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/SCT?alt=media&token=c9d6b605-df76-473f-89fb-86d8b3f795a4',
  },
  {
    name: 'Vanuatu',
    alpha2Code: 'VU',
    alpha3Code: 'VUT',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/VUT?alt=media&token=df3c0929-76ea-465d-915c-6663ce4698c0',
  },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    alpha2Code: 'VE',
    alpha3Code: 'VEN',
    region: 'Americas',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/VEN?alt=media&token=92e6e8ee-3236-49c9-bc94-78d56e6568a7',
  },
  {
    name: 'Viet Nam',
    alpha2Code: 'VN',
    alpha3Code: 'VNM',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/VNM?alt=media&token=4d1e0fe7-a64a-42d1-9fae-6ce629e95745',
  },
  {
    name: 'Wallis and Futuna',
    alpha2Code: 'WF',
    alpha3Code: 'WLF',
    region: 'Oceania',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/WLF?alt=media&token=82bec931-f88e-40f6-85f3-bf5fca9e7adc',
  },
  {
    name: 'Wales',
    alpha2Code: 'WL',
    alpha3Code: 'WLS',
    region: 'Europe',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/WLS?alt=media&token=8bb38521-1930-467f-bd8f-463773f082ad',
  },
  {
    name: 'Western Sahara',
    alpha2Code: 'EH',
    alpha3Code: 'ESH',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ESH?alt=media&token=80986146-409a-4a22-aff3-43d44724689f',
  },
  {
    name: 'Yemen',
    alpha2Code: 'YE',
    alpha3Code: 'YEM',
    region: 'Asia',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/YEM?alt=media&token=262783e7-3a13-439d-9972-a80609b0da35',
  },
  {
    name: 'Zambia',
    alpha2Code: 'ZM',
    alpha3Code: 'ZMB',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ZMB?alt=media&token=b9e2853a-5b39-4060-848f-32f132360ca7',
  },
  {
    name: 'Zimbabwe',
    alpha2Code: 'ZW',
    alpha3Code: 'ZWE',
    region: 'Africa',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/ZWE?alt=media&token=fd9aab6d-a796-4914-8327-dd036c4b91f6',
  },
];
