export const countries = [
  {
    name: 'Afghanistan',
    alpha2Code: 'AF',
    alpha3Code: 'AFG',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938754/country-flags/AFG.png',
    phoneCode: '+93',
  },
  {
    name: 'Åland Islands',
    alpha2Code: 'AX',
    alpha3Code: 'ALA',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938757/country-flags/ALA.png',
    phoneCode: '+358',
  },
  {
    name: 'Albania',
    alpha2Code: 'AL',
    alpha3Code: 'ALB',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938760/country-flags/ALB.png',
    phoneCode: '+355',
  },
  {
    name: 'Algeria',
    alpha2Code: 'DZ',
    alpha3Code: 'DZA',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938764/country-flags/DZA.png',
    phoneCode: '+213',
  },
  {
    name: 'American Samoa',
    alpha2Code: 'AS',
    alpha3Code: 'ASM',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938767/country-flags/ASM.png',
    phoneCode: '+1 684',
  },
  {
    name: 'Andorra',
    alpha2Code: 'AD',
    alpha3Code: 'AND',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938770/country-flags/AND.png',
    phoneCode: '+376',
  },
  {
    name: 'Angola',
    alpha2Code: 'AO',
    alpha3Code: 'AGO',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938774/country-flags/AGO.png',
    phoneCode: '+244',
  },
  {
    name: 'Anguilla',
    alpha2Code: 'AI',
    alpha3Code: 'AIA',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938778/country-flags/AIA.png',
    phoneCode: '+1 264',
  },
  {
    name: 'Antarctica',
    alpha2Code: 'AQ',
    alpha3Code: 'ATA',
    region: 'Polar',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/AQ?alt=media&token=d860faa4-77f8-4a44-923c-6558402184fd',
    phoneCode: '+672',
  },
  {
    name: 'Antigua and Barbuda',
    alpha2Code: 'AG',
    alpha3Code: 'ATG',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938781/country-flags/ATG.png',
    phoneCode: '+1268',
  },
  {
    name: 'Argentina',
    alpha2Code: 'AR',
    alpha3Code: 'ARG',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938784/country-flags/ARG.png',
    phoneCode: '+54',
  },
  {
    name: 'Armenia',
    alpha2Code: 'AM',
    alpha3Code: 'ARM',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938788/country-flags/ARM.png',
    phoneCode: '+374',
  },
  {
    name: 'Aruba',
    alpha2Code: 'AW',
    alpha3Code: 'ABW',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938791/country-flags/ABW.png',
    phoneCode: '+297',
  },
  {
    name: 'Australia',
    alpha2Code: 'AU',
    alpha3Code: 'AUS',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938794/country-flags/AUS.png',
    phoneCode: '+61',
  },
  {
    name: 'Austria',
    alpha2Code: 'AT',
    alpha3Code: 'AUT',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938797/country-flags/AUT.png',
    phoneCode: '+43',
  },
  {
    name: 'Azerbaijan',
    alpha2Code: 'AZ',
    alpha3Code: 'AZE',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938800/country-flags/AZE.png',
    phoneCode: '+994',
  },
  {
    name: 'Bahamas',
    alpha2Code: 'BS',
    alpha3Code: 'BHS',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938803/country-flags/BHS.png',
    phoneCode: '+1 242',
  },
  {
    name: 'Bahrain',
    alpha2Code: 'BH',
    alpha3Code: 'BHR',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938806/country-flags/BHR.png',
    phoneCode: '+973',
  },
  {
    name: 'Bangladesh',
    alpha2Code: 'BD',
    alpha3Code: 'BGD',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938810/country-flags/BGD.png',
    phoneCode: '+880',
  },
  {
    name: 'Barbados',
    alpha2Code: 'BB',
    alpha3Code: 'BRB',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938813/country-flags/BRB.png',
    phoneCode: '+1 246',
  },
  {
    name: 'Belarus',
    alpha2Code: 'BY',
    alpha3Code: 'BLR',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938817/country-flags/BLR.png',
    phoneCode: '+375',
  },
  {
    name: 'Belgium',
    alpha2Code: 'BE',
    alpha3Code: 'BEL',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938821/country-flags/BEL.png',
    phoneCode: '+32',
  },
  {
    name: 'Belize',
    alpha2Code: 'BZ',
    alpha3Code: 'BLZ',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938824/country-flags/BLZ.png',
    phoneCode: '+501',
  },
  {
    name: 'Benin',
    alpha2Code: 'BJ',
    alpha3Code: 'BEN',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938827/country-flags/BEN.png',
    phoneCode: '+229',
  },
  {
    name: 'Bermuda',
    alpha2Code: 'BM',
    alpha3Code: 'BMU',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938831/country-flags/BMU.png',
    phoneCode: '+1 441',
  },
  {
    name: 'Bhutan',
    alpha2Code: 'BT',
    alpha3Code: 'BTN',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938834/country-flags/BTN.png',
    phoneCode: '+975',
  },
  {
    name: 'Bolivia (Plurinational State of)',
    alpha2Code: 'BO',
    alpha3Code: 'BOL',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938838/country-flags/BOL.png',
    phoneCode: '+591',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    alpha2Code: 'BQ',
    alpha3Code: 'BES',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938841/country-flags/BES.png',
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2Code: 'BA',
    alpha3Code: 'BIH',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938844/country-flags/BIH.png',
    phoneCode: '+387',
  },
  {
    name: 'Botswana',
    alpha2Code: 'BW',
    alpha3Code: 'BWA',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938848/country-flags/BWA.png',
    phoneCode: '+267',
  },
  {
    name: 'Bouvet Island',
    alpha2Code: 'BV',
    alpha3Code: 'BVT',
    region: '',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BV?alt=media&token=1eb4dc36-90b4-44e8-bf17-0c983b9af8c9',
  },
  {
    name: 'Brazil',
    alpha2Code: 'BR',
    alpha3Code: 'BRA',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938851/country-flags/BRA.png',
    phoneCode: '+55',
  },
  {
    name: 'British Indian Ocean Territory',
    alpha2Code: 'IO',
    alpha3Code: 'IOT',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938854/country-flags/IOT.png',
    phoneCode: '+246',
  },
  {
    name: 'Brunei Darussalam',
    alpha2Code: 'BN',
    alpha3Code: 'BRN',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938867/country-flags/BRN.png',
    phoneCode: '+673',
  },
  {
    name: 'Bulgaria',
    alpha2Code: 'BG',
    alpha3Code: 'BGR',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938870/country-flags/BGR.png',
    phoneCode: '+359',
  },
  {
    name: 'Burkina Faso',
    alpha2Code: 'BF',
    alpha3Code: 'BFA',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938873/country-flags/BFA.png',
    phoneCode: '+226',
  },
  {
    name: 'Burundi',
    alpha2Code: 'BI',
    alpha3Code: 'BDI',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938876/country-flags/BDI.png',
    phoneCode: '+257',
  },
  {
    name: 'Cabo Verde',
    alpha2Code: 'CV',
    alpha3Code: 'CPV',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938889/country-flags/CPV.png',
    phoneCode: '+238',
  },
  {
    name: 'Cambodia',
    alpha2Code: 'KH',
    alpha3Code: 'KHM',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938880/country-flags/KHM.png',
    phoneCode: '+855',
  },
  {
    name: 'Cameroon',
    alpha2Code: 'CM',
    alpha3Code: 'CMR',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938883/country-flags/CMR.png',
    phoneCode: '+237',
  },
  {
    name: 'Canada',
    alpha2Code: 'CA',
    alpha3Code: 'CAN',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938886/country-flags/CAN.png',
    phoneCode: '+1',
  },
  {
    name: 'Cayman Islands',
    alpha2Code: 'KY',
    alpha3Code: 'CYM',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938892/country-flags/CYM.png',
    phoneCode: '+ 345',
  },
  {
    name: 'Central African Republic',
    alpha2Code: 'CF',
    alpha3Code: 'CAF',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938895/country-flags/CAF.png',
    phoneCode: '+236',
  },
  {
    name: 'Chad',
    alpha2Code: 'TD',
    alpha3Code: 'TCD',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938899/country-flags/TCD.png',
    phoneCode: '+235',
  },
  {
    name: 'Chile',
    alpha2Code: 'CL',
    alpha3Code: 'CHL',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938902/country-flags/CHL.png',
    phoneCode: '+56',
  },
  {
    name: 'China',
    alpha2Code: 'CN',
    alpha3Code: 'CHN',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938905/country-flags/CHN.png',
    phoneCode: '+86',
  },
  {
    name: 'Christmas Island',
    alpha2Code: 'CX',
    alpha3Code: 'CXR',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938908/country-flags/CXR.png',
    phoneCode: '+61',
  },
  {
    name: 'Cocos (Keeling) Islands',
    alpha2Code: 'CC',
    alpha3Code: 'CCK',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938912/country-flags/CCK.png',
    phoneCode: '+61',
  },
  {
    name: 'Colombia',
    alpha2Code: 'CO',
    alpha3Code: 'COL',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938915/country-flags/COL.png',
    phoneCode: '+57',
  },
  {
    name: 'Comoros',
    alpha2Code: 'KM',
    alpha3Code: 'COM',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938919/country-flags/COM.png',
    phoneCode: '+269',
  },
  {
    name: 'Congo',
    alpha2Code: 'CG',
    alpha3Code: 'COG',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938922/country-flags/COG.png',
    phoneCode: '+242',
  },
  {
    name: 'Congo (Democratic Republic of the)',
    alpha2Code: 'CD',
    alpha3Code: 'COD',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938925/country-flags/COD.png',
    phoneCode: '+243',
  },
  {
    name: 'Cook Islands',
    alpha2Code: 'CK',
    alpha3Code: 'COK',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938929/country-flags/COK.png',
    phoneCode: '+682',
  },
  {
    name: 'Costa Rica',
    alpha2Code: 'CR',
    alpha3Code: 'CRI',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938932/country-flags/CRI.png',
    phoneCode: '+506',
  },
  {
    name: "Côte d'Ivoire",
    alpha2Code: 'CI',
    alpha3Code: 'CIV',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939097/country-flags/CIV.png',
    phoneCode: '+225',
  },
  {
    name: 'Croatia',
    alpha2Code: 'HR',
    alpha3Code: 'HRV',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938935/country-flags/HRV.png',
    phoneCode: '+385',
  },
  {
    name: 'Cuba',
    alpha2Code: 'CU',
    alpha3Code: 'CUB',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938938/country-flags/CUB.png',
    phoneCode: '+53',
  },
  {
    name: 'Curaçao',
    alpha2Code: 'CW',
    alpha3Code: 'CUW',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938942/country-flags/CUW.png',
  },
  {
    name: 'Cyprus',
    alpha2Code: 'CY',
    alpha3Code: 'CYP',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938945/country-flags/CYP.png',
    phoneCode: '+357',
  },
  {
    name: 'Czech Republic',
    alpha2Code: 'CZ',
    alpha3Code: 'CZE',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938948/country-flags/CZE.png',
    phoneCode: '+420',
  },
  {
    name: 'Denmark',
    alpha2Code: 'DK',
    alpha3Code: 'DNK',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938952/country-flags/DNK.png',
    phoneCode: '+45',
  },
  {
    name: 'Djibouti',
    alpha2Code: 'DJ',
    alpha3Code: 'DJI',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938955/country-flags/DJI.png',
    phoneCode: '+253',
  },
  {
    name: 'Dominica',
    alpha2Code: 'DM',
    alpha3Code: 'DMA',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938958/country-flags/DMA.png',
    phoneCode: '+1 767',
  },
  {
    name: 'Dominican Republic',
    alpha2Code: 'DO',
    alpha3Code: 'DOM',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938961/country-flags/DOM.png',
    phoneCode: '+1 849',
  },
  {
    name: 'Ecuador',
    alpha2Code: 'EC',
    alpha3Code: 'ECU',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938967/country-flags/ECU.png',
    phoneCode: '+593',
  },
  {
    name: 'Egypt',
    alpha2Code: 'EG',
    alpha3Code: 'EGY',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938971/country-flags/EGY.png',
    phoneCode: '+20',
  },
  {
    name: 'El Salvador',
    alpha2Code: 'SV',
    alpha3Code: 'SLV',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938974/country-flags/SLV.png',
    phoneCode: '+503',
  },
  {
    name: 'England',
    alpha2Code: 'EN',
    alpha3Code: 'ENG',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1647403623/country-flags/ENG_nyupcl.png',
    phoneCode: '+44',
  },
  {
    name: 'Equatorial Guinea',
    alpha2Code: 'GQ',
    alpha3Code: 'GNQ',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938981/country-flags/GNQ.png',
    phoneCode: '+240',
  },
  {
    name: 'Eritrea',
    alpha2Code: 'ER',
    alpha3Code: 'ERI',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938984/country-flags/ERI.png',
    phoneCode: '+291',
  },
  {
    name: 'Estonia',
    alpha2Code: 'EE',
    alpha3Code: 'EST',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938987/country-flags/EST.png',
    phoneCode: '+372',
  },
  {
    name: 'Ethiopia',
    alpha2Code: 'ET',
    alpha3Code: 'ETH',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938990/country-flags/ETH.png',
    phoneCode: '+251',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    alpha2Code: 'FK',
    alpha3Code: 'FLK',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938993/country-flags/FLK.png',
    phoneCode: '+500',
  },
  {
    name: 'Faroe Islands',
    alpha2Code: 'FO',
    alpha3Code: 'FRO',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938997/country-flags/FRO.png',
    phoneCode: '+298',
  },
  {
    name: 'Fiji',
    alpha2Code: 'FJ',
    alpha3Code: 'FJI',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939000/country-flags/FJI.png',
    phoneCode: '+679',
  },
  {
    name: 'Finland',
    alpha2Code: 'FI',
    alpha3Code: 'FIN',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939004/country-flags/FIN.png',
    phoneCode: '+358',
  },
  {
    name: 'France',
    alpha2Code: 'FR',
    alpha3Code: 'FRA',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939007/country-flags/FRA.png',
    phoneCode: '+33',
  },
  {
    name: 'French Guiana',
    alpha2Code: 'GF',
    alpha3Code: 'GUF',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939010/country-flags/GUF.png',
    phoneCode: '+594',
  },
  {
    name: 'French Polynesia',
    alpha2Code: 'PF',
    alpha3Code: 'PYF',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939013/country-flags/PYF.png',
    phoneCode: '+689',
  },
  {
    name: 'French Southern Territories',
    alpha2Code: 'TF',
    alpha3Code: 'ATF',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939017/country-flags/ATF.png',
  },
  {
    name: 'Gabon',
    alpha2Code: 'GA',
    alpha3Code: 'GAB',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939020/country-flags/GAB.png',
    phoneCode: '+241',
  },
  {
    name: 'Gambia',
    alpha2Code: 'GM',
    alpha3Code: 'GMB',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939023/country-flags/GMB.png',
    phoneCode: '+220',
  },
  {
    name: 'Georgia',
    alpha2Code: 'GE',
    alpha3Code: 'GEO',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939026/country-flags/GEO.png',
    phoneCode: '+995',
  },
  {
    name: 'Germany',
    alpha2Code: 'DE',
    alpha3Code: 'DEU',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939030/country-flags/DEU.png',
    phoneCode: '+49',
  },
  {
    name: 'Ghana',
    alpha2Code: 'GH',
    alpha3Code: 'GHA',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939033/country-flags/GHA.png',
    phoneCode: '+233',
  },
  {
    name: 'Gibraltar',
    alpha2Code: 'GI',
    alpha3Code: 'GIB',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939036/country-flags/GIB.png',
    phoneCode: '+350',
  },
  {
    name: 'Greece',
    alpha2Code: 'GR',
    alpha3Code: 'GRC',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939039/country-flags/GRC.png',
    phoneCode: '+30',
  },
  {
    name: 'Greenland',
    alpha2Code: 'GL',
    alpha3Code: 'GRL',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939043/country-flags/GRL.png',
    phoneCode: '+299',
  },
  {
    name: 'Grenada',
    alpha2Code: 'GD',
    alpha3Code: 'GRD',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939046/country-flags/GRD.png',
    phoneCode: '+1 473',
  },
  {
    name: 'Guadeloupe',
    alpha2Code: 'GP',
    alpha3Code: 'GLP',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939049/country-flags/GLP.png',
    phoneCode: '+590',
  },
  {
    name: 'Guam',
    alpha2Code: 'GU',
    alpha3Code: 'GUM',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939053/country-flags/GUM.png',
    phoneCode: '+1 671',
  },
  {
    name: 'Guatemala',
    alpha2Code: 'GT',
    alpha3Code: 'GTM',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939056/country-flags/GTM.png',
    phoneCode: '+502',
  },
  {
    name: 'Guernsey',
    alpha2Code: 'GG',
    alpha3Code: 'GGY',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939059/country-flags/GGY.png',
    phoneCode: '+44',
  },
  {
    name: 'Guinea',
    alpha2Code: 'GN',
    alpha3Code: 'GIN',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939062/country-flags/GIN.png',
    phoneCode: '+224',
  },
  {
    name: 'Guinea-Bissau',
    alpha2Code: 'GW',
    alpha3Code: 'GNB',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939066/country-flags/GNB.png',
    phoneCode: '+245',
  },
  {
    name: 'Guyana',
    alpha2Code: 'GY',
    alpha3Code: 'GUY',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939069/country-flags/GUY.png',
    phoneCode: '+595',
  },
  {
    name: 'Haiti',
    alpha2Code: 'HT',
    alpha3Code: 'HTI',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939072/country-flags/HTI.png',
    phoneCode: '+509',
  },
  {
    name: 'Heard Island and McDonald Islands',
    alpha2Code: 'HM',
    alpha3Code: 'HMD',
    region: '',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/HM?alt=media&token=c9cce45b-6ff5-429e-9a15-819908701032',
  },
  {
    name: 'Holy See',
    alpha2Code: 'VA',
    alpha3Code: 'VAT',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939075/country-flags/VAT.png',
    phoneCode: '+379',
  },
  {
    name: 'Honduras',
    alpha2Code: 'HN',
    alpha3Code: 'HND',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939078/country-flags/HND.png',
    phoneCode: '+504',
  },
  {
    name: 'Hong Kong',
    alpha2Code: 'HK',
    alpha3Code: 'HKG',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939082/country-flags/HKG.png',
    phoneCode: '+852',
  },
  {
    name: 'Hungary',
    alpha2Code: 'HU',
    alpha3Code: 'HUN',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939085/country-flags/HUN.png',
    phoneCode: '+36',
  },
  {
    name: 'Iceland',
    alpha2Code: 'IS',
    alpha3Code: 'ISL',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939088/country-flags/ISL.png',
    phoneCode: '+354',
  },
  {
    name: 'India',
    alpha2Code: 'IN',
    alpha3Code: 'IND',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939091/country-flags/IND.png',
    phoneCode: '+91',
  },
  {
    name: 'Indonesia',
    alpha2Code: 'ID',
    alpha3Code: 'IDN',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939094/country-flags/IDN.png',
    phoneCode: '+62',
  },
  {
    name: 'Iran (Islamic Republic of)',
    alpha2Code: 'IR',
    alpha3Code: 'IRN',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939101/country-flags/IRN.png',
    phoneCode: '+98',
  },
  {
    name: 'Iraq',
    alpha2Code: 'IQ',
    alpha3Code: 'IRQ',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939105/country-flags/IRQ.png',
    phoneCode: '+964',
  },
  {
    name: 'Ireland',
    alpha2Code: 'IE',
    alpha3Code: 'IRL',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939108/country-flags/IRL.png',
    phoneCode: '+353',
  },
  {
    name: 'Isle of Man',
    alpha2Code: 'IM',
    alpha3Code: 'IMN',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939111/country-flags/IMN.png',
    phoneCode: '+44',
  },
  {
    name: 'Israel',
    alpha2Code: 'IL',
    alpha3Code: 'ISR',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939114/country-flags/ISR.png',
    phoneCode: '+972',
  },
  {
    name: 'Italy',
    alpha2Code: 'IT',
    alpha3Code: 'ITA',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939117/country-flags/ITA.png',
    phoneCode: '+39',
  },
  {
    name: 'Jamaica',
    alpha2Code: 'JM',
    alpha3Code: 'JAM',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939120/country-flags/JAM.png',
    phoneCode: '+1 876',
  },
  {
    name: 'Japan',
    alpha2Code: 'JP',
    alpha3Code: 'JPN',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939124/country-flags/JPN.png',
    phoneCode: '+81',
  },
  {
    name: 'Jersey',
    alpha2Code: 'JE',
    alpha3Code: 'JEY',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939127/country-flags/JEY.png',
    phoneCode: '+44',
  },
  {
    name: 'Jordan',
    alpha2Code: 'JO',
    alpha3Code: 'JOR',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939130/country-flags/JOR.png',
    phoneCode: '+962',
  },
  {
    name: 'Kazakhstan',
    alpha2Code: 'KZ',
    alpha3Code: 'KAZ',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939133/country-flags/KAZ.png',
    phoneCode: '+7 7',
  },
  {
    name: 'Kenya',
    alpha2Code: 'KE',
    alpha3Code: 'KEN',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939136/country-flags/KEN.png',
    phoneCode: '+254',
  },
  {
    name: 'Kiribati',
    alpha2Code: 'KI',
    alpha3Code: 'KIR',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939140/country-flags/KIR.png',
    phoneCode: '+686',
  },
  {
    name: "Korea (Democratic People's Republic of)",
    alpha2Code: 'KP',
    alpha3Code: 'PRK',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939291/country-flags/PRK.png',
    phoneCode: '+850',
  },
  {
    name: 'Korea (Republic of)',
    alpha2Code: 'KR',
    alpha3Code: 'KOR',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939441/country-flags/KOR.png',
    phoneCode: '+82',
  },
  {
    name: 'Kuwait',
    alpha2Code: 'KW',
    alpha3Code: 'KWT',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939143/country-flags/KWT.png',
    phoneCode: '+965',
  },
  {
    name: 'Kyrgyzstan',
    alpha2Code: 'KG',
    alpha3Code: 'KGZ',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939146/country-flags/KGZ.png',
    phoneCode: '+996',
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2Code: 'LA',
    alpha3Code: 'LAO',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939149/country-flags/LAO.png',
    phoneCode: '+856',
  },
  {
    name: 'Latvia',
    alpha2Code: 'LV',
    alpha3Code: 'LVA',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939152/country-flags/LVA.png',
    phoneCode: '+371',
  },
  {
    name: 'Lebanon',
    alpha2Code: 'LB',
    alpha3Code: 'LBN',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939155/country-flags/LBN.png',
    phoneCode: '+961',
  },
  {
    name: 'Lesotho',
    alpha2Code: 'LS',
    alpha3Code: 'LSO',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939159/country-flags/LSO.png',
    phoneCode: '+266',
  },
  {
    name: 'Liberia',
    alpha2Code: 'LR',
    alpha3Code: 'LBR',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939162/country-flags/LBR.png',
    phoneCode: '+231',
  },
  {
    name: 'Libya',
    alpha2Code: 'LY',
    alpha3Code: 'LBY',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939165/country-flags/LBY.png',
    phoneCode: '+218',
  },
  {
    name: 'Liechtenstein',
    alpha2Code: 'LI',
    alpha3Code: 'LIE',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939168/country-flags/LIE.png',
    phoneCode: '+423',
  },
  {
    name: 'Lithuania',
    alpha2Code: 'LT',
    alpha3Code: 'LTU',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939172/country-flags/LTU.png',
    phoneCode: '+370',
  },
  {
    name: 'Luxembourg',
    alpha2Code: 'LU',
    alpha3Code: 'LUX',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939175/country-flags/LUX.png',
    phoneCode: '+352',
  },
  {
    name: 'Macao',
    alpha2Code: 'MO',
    alpha3Code: 'MAC',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939178/country-flags/MAC.png',
    phoneCode: '+853',
  },
  {
    name: 'Macedonia (the former Yugoslav Republic of)',
    alpha2Code: 'MK',
    alpha3Code: 'MKD',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939181/country-flags/MKD.png',
    phoneCode: '+389',
  },
  {
    name: 'Madagascar',
    alpha2Code: 'MG',
    alpha3Code: 'MDG',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939184/country-flags/MDG.png',
    phoneCode: '+261',
  },
  {
    name: 'Malawi',
    alpha2Code: 'MW',
    alpha3Code: 'MWI',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939187/country-flags/MWI.png',
    phoneCode: '+265',
  },
  {
    name: 'Malaysia',
    alpha2Code: 'MY',
    alpha3Code: 'MYS',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939191/country-flags/MYS.png',
    phoneCode: '+60',
  },
  {
    name: 'Maldives',
    alpha2Code: 'MV',
    alpha3Code: 'MDV',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939195/country-flags/MDV.png',
    phoneCode: '+960',
  },
  {
    name: 'Mali',
    alpha2Code: 'ML',
    alpha3Code: 'MLI',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939198/country-flags/MLI.png',
    phoneCode: '+223',
  },
  {
    name: 'Malta',
    alpha2Code: 'MT',
    alpha3Code: 'MLT',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939201/country-flags/MLT.png',
    phoneCode: '+356',
  },
  {
    name: 'Marshall Islands',
    alpha2Code: 'MH',
    alpha3Code: 'MHL',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939205/country-flags/MHL.png',
    phoneCode: '+692',
  },
  {
    name: 'Martinique',
    alpha2Code: 'MQ',
    alpha3Code: 'MTQ',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939208/country-flags/MTQ.png',
    phoneCode: '+596',
  },
  {
    name: 'Mauritania',
    alpha2Code: 'MR',
    alpha3Code: 'MRT',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939211/country-flags/MRT.png',
    phoneCode: '+222',
  },
  {
    name: 'Mauritius',
    alpha2Code: 'MU',
    alpha3Code: 'MUS',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939214/country-flags/MUS.png',
    phoneCode: '+230',
  },
  {
    name: 'Mayotte',
    alpha2Code: 'YT',
    alpha3Code: 'MYT',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939218/country-flags/MYT.png',
    phoneCode: '+262',
  },
  {
    name: 'Mexico',
    alpha2Code: 'MX',
    alpha3Code: 'MEX',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939221/country-flags/MEX.png',
    phoneCode: '+52',
  },
  {
    name: 'Micronesia (Federated States of)',
    alpha2Code: 'FM',
    alpha3Code: 'FSM',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939225/country-flags/FSM.png',
    phoneCode: '+691',
  },
  {
    name: 'Moldova (Republic of)',
    alpha2Code: 'MD',
    alpha3Code: 'MDA',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939228/country-flags/MDA.png',
    phoneCode: '+373',
  },
  {
    name: 'Monaco',
    alpha2Code: 'MC',
    alpha3Code: 'MCO',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939232/country-flags/MCO.png',
    phoneCode: '+377',
  },
  {
    name: 'Mongolia',
    alpha2Code: 'MN',
    alpha3Code: 'MNG',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939236/country-flags/MNG.png',
    phoneCode: '+976',
  },
  {
    name: 'Montenegro',
    alpha2Code: 'ME',
    alpha3Code: 'MNE',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939239/country-flags/MNE.png',
    phoneCode: '+382',
  },
  {
    name: 'Montserrat',
    alpha2Code: 'MS',
    alpha3Code: 'MSR',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939242/country-flags/MSR.png',
    phoneCode: '+1664',
  },
  {
    name: 'Morocco',
    alpha2Code: 'MA',
    alpha3Code: 'MAR',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939246/country-flags/MAR.png',
    phoneCode: '+212',
  },
  {
    name: 'Mozambique',
    alpha2Code: 'MZ',
    alpha3Code: 'MOZ',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939249/country-flags/MOZ.png',
    phoneCode: '+258',
  },
  {
    name: 'Myanmar',
    alpha2Code: 'MM',
    alpha3Code: 'MMR',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939252/country-flags/MMR.png',
    phoneCode: '+95',
  },
  {
    name: 'Namibia',
    alpha2Code: 'NA',
    alpha3Code: 'NAM',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939255/country-flags/NAM.png',
    phoneCode: '+264',
  },
  {
    name: 'Nauru',
    alpha2Code: 'NR',
    alpha3Code: 'NRU',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939259/country-flags/NRU.png',
    phoneCode: '+674',
  },
  {
    name: 'Nepal',
    alpha2Code: 'NP',
    alpha3Code: 'NPL',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939262/country-flags/NPL.png',
    phoneCode: '+977',
  },
  {
    name: 'Netherlands',
    alpha2Code: 'NL',
    alpha3Code: 'NLD',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939266/country-flags/NLD.png',
    phoneCode: '+31',
  },
  {
    name: 'New Caledonia',
    alpha2Code: 'NC',
    alpha3Code: 'NCL',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939269/country-flags/NCL.png',
    phoneCode: '+687',
  },
  {
    name: 'New Zealand',
    alpha2Code: 'NZ',
    alpha3Code: 'NZL',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939272/country-flags/NZL.png',
    phoneCode: '+64',
  },
  {
    name: 'Nicaragua',
    alpha2Code: 'NI',
    alpha3Code: 'NIC',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939275/country-flags/NIC.png',
    phoneCode: '+505',
  },
  {
    name: 'Niger',
    alpha2Code: 'NE',
    alpha3Code: 'NER',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939278/country-flags/NER.png',
    phoneCode: '+227',
  },
  {
    name: 'Nigeria',
    alpha2Code: 'NG',
    alpha3Code: 'NGA',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939281/country-flags/NGA.png',
    phoneCode: '+234',
  },
  {
    name: 'Niue',
    alpha2Code: 'NU',
    alpha3Code: 'NIU',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939285/country-flags/NIU.png',
    phoneCode: '+683',
  },
  {
    name: 'Norfolk Island',
    alpha2Code: 'NF',
    alpha3Code: 'NFK',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939288/country-flags/NFK.png',
    phoneCode: '+672',
  },
  {
    name: 'Northern Mariana Islands',
    alpha2Code: 'MP',
    alpha3Code: 'MNP',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939294/country-flags/MNP.png',
    phoneCode: '+1 670',
  },
  {
    name: 'Norway',
    alpha2Code: 'NO',
    alpha3Code: 'NOR',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939298/country-flags/NOR.png',
    phoneCode: '+47',
  },
  {
    name: 'Oman',
    alpha2Code: 'OM',
    alpha3Code: 'OMN',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939301/country-flags/OMN.png',
    phoneCode: '+968',
  },
  {
    name: 'Pakistan',
    alpha2Code: 'PK',
    alpha3Code: 'PAK',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939304/country-flags/PAK.png',
    phoneCode: '+92',
  },
  {
    name: 'Palau',
    alpha2Code: 'PW',
    alpha3Code: 'PLW',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939307/country-flags/PLW.png',
    phoneCode: '+680',
  },
  {
    name: 'Palestine, State of',
    alpha2Code: 'PS',
    alpha3Code: 'PSE',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939310/country-flags/PSE.png',
    phoneCode: '+970',
  },
  {
    name: 'Panama',
    alpha2Code: 'PA',
    alpha3Code: 'PAN',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939314/country-flags/PAN.png',
    phoneCode: '+507',
  },
  {
    name: 'Papua New Guinea',
    alpha2Code: 'PG',
    alpha3Code: 'PNG',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939317/country-flags/PNG.png',
    phoneCode: '+675',
  },
  {
    name: 'Paraguay',
    alpha2Code: 'PY',
    alpha3Code: 'PRY',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939320/country-flags/PRY.png',
    phoneCode: '+595',
  },
  {
    name: 'Peru',
    alpha2Code: 'PE',
    alpha3Code: 'PER',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939323/country-flags/PER.png',
    phoneCode: '+51',
  },
  {
    name: 'Philippines',
    alpha2Code: 'PH',
    alpha3Code: 'PHL',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939327/country-flags/PHL.png',
    phoneCode: '+63',
  },
  {
    name: 'Pitcairn',
    alpha2Code: 'PN',
    alpha3Code: 'PCN',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939332/country-flags/PCN.png',
    phoneCode: '+872',
  },
  {
    name: 'Poland',
    alpha2Code: 'PL',
    alpha3Code: 'POL',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939335/country-flags/POL.png',
    phoneCode: '+48',
  },
  {
    name: 'Portugal',
    alpha2Code: 'PT',
    alpha3Code: 'PRT',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939338/country-flags/PRT.png',
    phoneCode: '+351',
  },
  {
    name: 'Puerto Rico',
    alpha2Code: 'PR',
    alpha3Code: 'PRI',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939342/country-flags/PRI.png',
    phoneCode: '+1 939',
  },
  {
    name: 'Qatar',
    alpha2Code: 'QA',
    alpha3Code: 'QAT',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939345/country-flags/QAT.png',
    phoneCode: '+974',
  },
  {
    name: 'Republic of Kosovo',
    alpha2Code: 'XK',
    alpha3Code: 'KOS',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939348/country-flags/KOS.png',
  },
  {
    name: 'Réunion',
    alpha2Code: 'RE',
    alpha3Code: 'REU',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939352/country-flags/REU.png',
    phoneCode: '+262',
  },
  {
    name: 'Romania',
    alpha2Code: 'RO',
    alpha3Code: 'ROU',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939354/country-flags/ROU.png',
    phoneCode: '+40',
  },
  {
    name: 'Russian Federation',
    alpha2Code: 'RU',
    alpha3Code: 'RUS',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939358/country-flags/RUS.png',
    phoneCode: '+7',
  },
  {
    name: 'Rwanda',
    alpha2Code: 'RW',
    alpha3Code: 'RWA',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939361/country-flags/RWA.png',
    phoneCode: '+250',
  },
  {
    name: 'Saint Barthélemy',
    alpha2Code: 'BL',
    alpha3Code: 'BLM',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939364/country-flags/BLM.png',
    phoneCode: '+590',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    alpha2Code: 'SH',
    alpha3Code: 'SHN',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939367/country-flags/SHN.png',
    phoneCode: '+290',
  },
  {
    name: 'Saint Kitts and Nevis',
    alpha2Code: 'KN',
    alpha3Code: 'KNA',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939371/country-flags/KNA.png',
    phoneCode: '+1 869',
  },
  {
    name: 'Saint Lucia',
    alpha2Code: 'LC',
    alpha3Code: 'LCA',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939374/country-flags/LCA.png',
    phoneCode: '+1 758',
  },
  {
    name: 'Saint Martin (French part)',
    alpha2Code: 'MF',
    alpha3Code: 'MAF',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939377/country-flags/MAF.png',
    phoneCode: '+590',
  },
  {
    name: 'Saint Pierre and Miquelon',
    alpha2Code: 'PM',
    alpha3Code: 'SPM',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939381/country-flags/SPM.png',
    phoneCode: '+508',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    alpha2Code: 'VC',
    alpha3Code: 'VCT',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939384/country-flags/VCT.png',
    phoneCode: '+1 784',
  },
  {
    name: 'Samoa',
    alpha2Code: 'WS',
    alpha3Code: 'WSM',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939387/country-flags/WSM.png',
    phoneCode: '+685',
  },
  {
    name: 'San Marino',
    alpha2Code: 'SM',
    alpha3Code: 'SMR',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939390/country-flags/SMR.png',
    phoneCode: '+378',
  },
  {
    name: 'Sao Tome and Principe',
    alpha2Code: 'ST',
    alpha3Code: 'STP',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939394/country-flags/STP.png',
    phoneCode: '+239',
  },
  {
    name: 'Saudi Arabia',
    alpha2Code: 'SA',
    alpha3Code: 'SAU',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939397/country-flags/SAU.png',
    phoneCode: '+966',
  },
  {
    name: 'Senegal',
    alpha2Code: 'SN',
    alpha3Code: 'SEN',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939400/country-flags/SEN.png',
    phoneCode: '+221',
  },
  {
    name: 'Serbia',
    alpha2Code: 'RS',
    alpha3Code: 'SRB',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939403/country-flags/SRB.png',
    phoneCode: '+381',
  },
  {
    name: 'Seychelles',
    alpha2Code: 'SC',
    alpha3Code: 'SYC',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939406/country-flags/SYC.png',
    phoneCode: '+248',
  },
  {
    name: 'Sierra Leone',
    alpha2Code: 'SL',
    alpha3Code: 'SLE',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939410/country-flags/SLE.png',
    phoneCode: '+232',
  },
  {
    name: 'Singapore',
    alpha2Code: 'SG',
    alpha3Code: 'SGP',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939413/country-flags/SGP.png',
    phoneCode: '+65',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    alpha2Code: 'SX',
    alpha3Code: 'SXM',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939416/country-flags/SXM.png',
  },
  {
    name: 'Slovakia',
    alpha2Code: 'SK',
    alpha3Code: 'SVK',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939420/country-flags/SVK.png',
    phoneCode: '+421',
  },
  {
    name: 'Slovenia',
    alpha2Code: 'SI',
    alpha3Code: 'SVN',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939423/country-flags/SVN.png',
    phoneCode: '+386',
  },
  {
    name: 'Solomon Islands',
    alpha2Code: 'SB',
    alpha3Code: 'SLB',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939426/country-flags/SLB.png',
    phoneCode: '+677',
  },
  {
    name: 'Somalia',
    alpha2Code: 'SO',
    alpha3Code: 'SOM',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939429/country-flags/SOM.png',
    phoneCode: '+252',
  },
  {
    name: 'South Africa',
    alpha2Code: 'ZA',
    alpha3Code: 'ZAF',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939432/country-flags/ZAF.png',
    phoneCode: '+27',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    alpha2Code: 'GS',
    alpha3Code: 'SGS',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939437/country-flags/SGS.png',
    phoneCode: '+500',
  },
  {
    name: 'South Sudan',
    alpha2Code: 'SS',
    alpha3Code: 'SSD',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939444/country-flags/SSD.png',
  },
  {
    name: 'Spain',
    alpha2Code: 'ES',
    alpha3Code: 'ESP',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939447/country-flags/ESP.png',
    phoneCode: '+34',
  },
  {
    name: 'Sri Lanka',
    alpha2Code: 'LK',
    alpha3Code: 'LKA',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939451/country-flags/LKA.png',
    phoneCode: '+94',
  },
  {
    name: 'Sudan',
    alpha2Code: 'SD',
    alpha3Code: 'SDN',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939454/country-flags/SDN.png',
    phoneCode: '+249',
  },
  {
    name: 'Suriname',
    alpha2Code: 'SR',
    alpha3Code: 'SUR',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939457/country-flags/SUR.png',
    phoneCode: '+597',
  },
  {
    name: 'Svalbard and Jan Mayen',
    alpha2Code: 'SJ',
    alpha3Code: 'SJM',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939460/country-flags/SJM.png',
    phoneCode: '+47',
  },
  {
    name: 'Swaziland',
    alpha2Code: 'SZ',
    alpha3Code: 'SWZ',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939463/country-flags/SWZ.png',
    phoneCode: '+268',
  },
  {
    name: 'Sweden',
    alpha2Code: 'SE',
    alpha3Code: 'SWE',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939466/country-flags/SWE.png',
    phoneCode: '+46',
  },
  {
    name: 'Switzerland',
    alpha2Code: 'CH',
    alpha3Code: 'CHE',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939470/country-flags/CHE.png',
    phoneCode: '+41',
  },
  {
    name: 'Syrian Arab Republic',
    alpha2Code: 'SY',
    alpha3Code: 'SYR',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939473/country-flags/SYR.png',
    phoneCode: '+963',
  },
  {
    name: 'Taiwan',
    alpha2Code: 'TW',
    alpha3Code: 'TWN',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939476/country-flags/TWN.png',
    phoneCode: '+886',
  },
  {
    name: 'Tajikistan',
    alpha2Code: 'TJ',
    alpha3Code: 'TJK',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939479/country-flags/TJK.png',
    phoneCode: '+992',
  },
  {
    name: 'Tanzania, United Republic of',
    alpha2Code: 'TZ',
    alpha3Code: 'TZA',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939482/country-flags/TZA.png',
    phoneCode: '+255',
  },
  {
    name: 'Thailand',
    alpha2Code: 'TH',
    alpha3Code: 'THA',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939485/country-flags/THA.png',
    phoneCode: '+66',
  },
  {
    name: 'Timor-Leste',
    alpha2Code: 'TL',
    alpha3Code: 'TLS',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939488/country-flags/TLS.png',
    phoneCode: '+670',
  },
  {
    name: 'Togo',
    alpha2Code: 'TG',
    alpha3Code: 'TGO',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939491/country-flags/TGO.png',
    phoneCode: '+228',
  },
  {
    name: 'Tokelau',
    alpha2Code: 'TK',
    alpha3Code: 'TKL',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939494/country-flags/TKL.png',
    phoneCode: '+690',
  },
  {
    name: 'Tonga',
    alpha2Code: 'TO',
    alpha3Code: 'TON',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939499/country-flags/TON.png',
    phoneCode: '+676',
  },
  {
    name: 'Trinidad and Tobago',
    alpha2Code: 'TT',
    alpha3Code: 'TTO',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939502/country-flags/TTO.png',
    phoneCode: '+1 868',
  },
  {
    name: 'Tunisia',
    alpha2Code: 'TN',
    alpha3Code: 'TUN',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939505/country-flags/TUN.png',
    phoneCode: '+216',
  },
  {
    name: 'Turkey',
    alpha2Code: 'TR',
    alpha3Code: 'TUR',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939508/country-flags/TUR.png',
    phoneCode: '+90',
  },
  {
    name: 'Turkmenistan',
    alpha2Code: 'TM',
    alpha3Code: 'TKM',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939512/country-flags/TKM.png',
    phoneCode: '+993',
  },
  {
    name: 'Turks and Caicos Islands',
    alpha2Code: 'TC',
    alpha3Code: 'TCA',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939515/country-flags/TCA.png',
    phoneCode: '+1 649',
  },
  {
    name: 'Tuvalu',
    alpha2Code: 'TV',
    alpha3Code: 'TUV',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939519/country-flags/TUV.png',
    phoneCode: '+688',
  },
  {
    name: 'Uganda',
    alpha2Code: 'UG',
    alpha3Code: 'UGA',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939522/country-flags/UGA.png',
    phoneCode: '+256',
  },
  {
    name: 'Ukraine',
    alpha2Code: 'UA',
    alpha3Code: 'UKR',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939525/country-flags/UKR.png',
    phoneCode: '+380',
  },
  {
    name: 'United Arab Emirates',
    alpha2Code: 'AE',
    alpha3Code: 'ARE',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939529/country-flags/ARE.png',
    phoneCode: '+971',
  },
  {
    name: 'Northern Ireland',
    alpha2Code: 'GB',
    alpha3Code: 'GBR',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939532/country-flags/GBR.png',
    phoneCode: '+44',
  },
  {
    name: 'United States Minor Outlying Islands',
    alpha2Code: 'UM',
    alpha3Code: 'UMI',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938857/country-flags/UMI.png',
  },
  {
    name: 'United States of America',
    alpha2Code: 'US',
    alpha3Code: 'USA',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939535/country-flags/USA.png',
    phoneCode: '+1',
  },
  {
    name: 'Uruguay',
    alpha2Code: 'UY',
    alpha3Code: 'URY',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939538/country-flags/URY.png',
    phoneCode: '+598',
  },
  {
    name: 'Uzbekistan',
    alpha2Code: 'UZ',
    alpha3Code: 'UZB',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939541/country-flags/UZB.png',
    phoneCode: '+998',
  },
  {
    name: 'Vanuatu',
    alpha2Code: 'VU',
    alpha3Code: 'VUT',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939548/country-flags/VUT.png',
    phoneCode: '+678',
  },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    alpha2Code: 'VE',
    alpha3Code: 'VEN',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939551/country-flags/VEN.png',
    phoneCode: '+58',
  },
  {
    name: 'Viet Nam',
    alpha2Code: 'VN',
    alpha3Code: 'VNM',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939554/country-flags/VNM.png',
    phoneCode: '+84',
  },
  {
    name: 'Virgin Islands (British)',
    alpha2Code: 'VG',
    alpha3Code: 'VGB',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938860/country-flags/VGB.png',
    phoneCode: '+1 284',
  },
  {
    name: 'Virgin Islands (U.S.)',
    alpha2Code: 'VI',
    alpha3Code: 'VIR',
    region: 'Americas',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938864/country-flags/VIR.png',
    phoneCode: '+1 340',
  },
  {
    name: 'Wallis and Futuna',
    alpha2Code: 'WF',
    alpha3Code: 'WLF',
    region: 'Oceania',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939557/country-flags/WLF.png',
    phoneCode: '+681',
  },
  {
    name: 'Western Sahara',
    alpha2Code: 'EH',
    alpha3Code: 'ESH',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939564/country-flags/ESH.png',
  },
  {
    name: 'Yemen',
    alpha2Code: 'YE',
    alpha3Code: 'YEM',
    region: 'Asia',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939567/country-flags/YEM.png',
    phoneCode: '+967',
  },
  {
    name: 'Zambia',
    alpha2Code: 'ZM',
    alpha3Code: 'ZMB',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939571/country-flags/ZMB.png',
    phoneCode: '+260',
  },
  {
    name: 'Zimbabwe',
    alpha2Code: 'ZW',
    alpha3Code: 'ZWE',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939574/country-flags/ZWE.png',
    phoneCode: '+263',
  },
  {
    name: 'Wales',
    alpha2Code: 'GB',
    alpha3Code: 'GBR',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939560/country-flags/WLS.png',
    phoneCode: '+44',
  },
  {
    name: 'Scotland',
    alpha2Code: 'GB',
    alpha3Code: 'GBR',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1647403623/country-flags/SCT.png',
    phoneCode: '+44',
  },
  {
    name: 'Eswatini',
    alpha2Code: 'SZ',
    alpha3Code: 'SWZ',
    region: 'Africa',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939463/country-flags/SWZ.png',
    phoneCode: '+268',
  },
  {
    name: 'North Macedonia',
    alpha2Code: 'MK',
    alpha3Code: 'MKD',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626939181/country-flags/MKD.png',
    phoneCode: '+389',
  },
  {
    name: 'Czechia',
    alpha2Code: 'CZ',
    alpha3Code: 'CZE',
    region: 'Europe',
    flag: 'https://res.cloudinary.com/zporter-media-cloud/image/upload/v1626938948/country-flags/CZE.png',
    phoneCode: '+420',
  },
];

export const defaultCountry = countries.find(
  (country) => country.name === 'Sweden',
);

export const defaultOpponentCountry = countries.find(
  (country) => country.name === 'Norway',
);
export const GDPRCountryName = [
  'Austria',
  'Belgium',
  'Bulgaria',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Hungary',
  'Ireland',
  'Italy',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Netherlands',
  'Poland',
  'Portugal',
  'Romania',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'Northern Ireland',
];
export const listNameCountry = countries.map((e) => e.name);
