const countries = [
  {
    name: 'Afghanistan',
    alpha2Code: 'AF',
    alpha3Code: 'AFG',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/af.svg',
    phoneCode: '+93',
  },
  {
    name: 'Åland Islands',
    alpha2Code: 'AX',
    alpha3Code: 'ALA',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ax.svg',
    phoneCode: '+358',
  },
  {
    name: 'Albania',
    alpha2Code: 'AL',
    alpha3Code: 'ALB',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/al.svg',
    phoneCode: '+355',
  },
  {
    name: 'Algeria',
    alpha2Code: 'DZ',
    alpha3Code: 'DZA',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/dz.svg',
    phoneCode: '+213',
  },
  {
    name: 'American Samoa',
    alpha2Code: 'AS',
    alpha3Code: 'ASM',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/as.svg',
    phoneCode: '+1 684',
  },
  {
    name: 'Andorra',
    alpha2Code: 'AD',
    alpha3Code: 'AND',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ad.svg',
    phoneCode: '+376',
  },
  {
    name: 'Angola',
    alpha2Code: 'AO',
    alpha3Code: 'AGO',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ao.svg',
    phoneCode: '+244',
  },
  {
    name: 'Anguilla',
    alpha2Code: 'AI',
    alpha3Code: 'AIA',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ai.svg',
    phoneCode: '+1 264',
  },
  {
    name: 'Antarctica',
    alpha2Code: 'AQ',
    alpha3Code: 'ATA',
    region: 'Polar',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/AQ?alt=media&token=d860faa4-77f8-4a44-923c-6558402184fd',
    phoneCode: '+672',
  },
  {
    name: 'Antigua and Barbuda',
    alpha2Code: 'AG',
    alpha3Code: 'ATG',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ag.svg',
    phoneCode: '+1268',
  },
  {
    name: 'Argentina',
    alpha2Code: 'AR',
    alpha3Code: 'ARG',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ar.svg',
    phoneCode: '+54',
  },
  {
    name: 'Armenia',
    alpha2Code: 'AM',
    alpha3Code: 'ARM',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/am.svg',
    phoneCode: '+374',
  },
  {
    name: 'Aruba',
    alpha2Code: 'AW',
    alpha3Code: 'ABW',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/aw.svg',
    phoneCode: '+297',
  },
  {
    name: 'Australia',
    alpha2Code: 'AU',
    alpha3Code: 'AUS',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/au.svg',
    phoneCode: '+61',
  },
  {
    name: 'Austria',
    alpha2Code: 'AT',
    alpha3Code: 'AUT',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/at.svg',
    phoneCode: '+43',
  },
  {
    name: 'Azerbaijan',
    alpha2Code: 'AZ',
    alpha3Code: 'AZE',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/az.svg',
    phoneCode: '+994',
  },
  {
    name: 'Bahamas',
    alpha2Code: 'BS',
    alpha3Code: 'BHS',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bs.svg',
    phoneCode: '+1 242',
  },
  {
    name: 'Bahrain',
    alpha2Code: 'BH',
    alpha3Code: 'BHR',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bh.svg',
    phoneCode: '+973',
  },
  {
    name: 'Bangladesh',
    alpha2Code: 'BD',
    alpha3Code: 'BGD',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bd.svg',
    phoneCode: '+880',
  },
  {
    name: 'Barbados',
    alpha2Code: 'BB',
    alpha3Code: 'BRB',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bb.svg',
    phoneCode: '+1 246',
  },
  {
    name: 'Belarus',
    alpha2Code: 'BY',
    alpha3Code: 'BLR',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/by.svg',
    phoneCode: '+375',
  },
  {
    name: 'Belgium',
    alpha2Code: 'BE',
    alpha3Code: 'BEL',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/be.svg',
    phoneCode: '+32',
  },
  {
    name: 'Belize',
    alpha2Code: 'BZ',
    alpha3Code: 'BLZ',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bz.svg',
    phoneCode: '+501',
  },
  {
    name: 'Benin',
    alpha2Code: 'BJ',
    alpha3Code: 'BEN',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bj.svg',
    phoneCode: '+229',
  },
  {
    name: 'Bermuda',
    alpha2Code: 'BM',
    alpha3Code: 'BMU',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bm.svg',
    phoneCode: '+1 441',
  },
  {
    name: 'Bhutan',
    alpha2Code: 'BT',
    alpha3Code: 'BTN',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bt.svg',
    phoneCode: '+975',
  },
  {
    name: 'Bolivia (Plurinational State of)',
    alpha2Code: 'BO',
    alpha3Code: 'BOL',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bo.svg',
    phoneCode: '+591',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    alpha2Code: 'BQ',
    alpha3Code: 'BES',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bq.svg',
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2Code: 'BA',
    alpha3Code: 'BIH',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ba.svg',
    phoneCode: '+387',
  },
  {
    name: 'Botswana',
    alpha2Code: 'BW',
    alpha3Code: 'BWA',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bw.svg',
    phoneCode: '+267',
  },
  {
    name: 'Bouvet Island',
    alpha2Code: 'BV',
    alpha3Code: 'BVT',
    region: '',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/BV?alt=media&token=1eb4dc36-90b4-44e8-bf17-0c983b9af8c9',
  },
  {
    name: 'Brazil',
    alpha2Code: 'BR',
    alpha3Code: 'BRA',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/br.svg',
    phoneCode: '+55',
  },
  {
    name: 'British Indian Ocean Territory',
    alpha2Code: 'IO',
    alpha3Code: 'IOT',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/io.svg',
    phoneCode: '+246',
  },
  {
    name: 'United States Minor Outlying Islands',
    alpha2Code: 'UM',
    alpha3Code: 'UMI',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/um.svg',
  },
  {
    name: 'Virgin Islands (British)',
    alpha2Code: 'VG',
    alpha3Code: 'VGB',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/vg.svg',
    phoneCode: '+1 284',
  },
  {
    name: 'Virgin Islands (U.S.)',
    alpha2Code: 'VI',
    alpha3Code: 'VIR',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/vi.svg',
    phoneCode: '+1 340',
  },
  {
    name: 'Brunei Darussalam',
    alpha2Code: 'BN',
    alpha3Code: 'BRN',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bn.svg',
    phoneCode: '+673',
  },
  {
    name: 'Bulgaria',
    alpha2Code: 'BG',
    alpha3Code: 'BGR',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bg.svg',
    phoneCode: '+359',
  },
  {
    name: 'Burkina Faso',
    alpha2Code: 'BF',
    alpha3Code: 'BFA',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bf.svg',
    phoneCode: '+226',
  },
  {
    name: 'Burundi',
    alpha2Code: 'BI',
    alpha3Code: 'BDI',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bi.svg',
    phoneCode: '+257',
  },
  {
    name: 'Cambodia',
    alpha2Code: 'KH',
    alpha3Code: 'KHM',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/kh.svg',
    phoneCode: '+855',
  },
  {
    name: 'Cameroon',
    alpha2Code: 'CM',
    alpha3Code: 'CMR',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cm.svg',
    phoneCode: '+237',
  },
  {
    name: 'Canada',
    alpha2Code: 'CA',
    alpha3Code: 'CAN',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ca.svg',
    phoneCode: '+1',
  },
  {
    name: 'Cabo Verde',
    alpha2Code: 'CV',
    alpha3Code: 'CPV',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cv.svg',
    phoneCode: '+238',
  },
  {
    name: 'Cayman Islands',
    alpha2Code: 'KY',
    alpha3Code: 'CYM',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ky.svg',
    phoneCode: '+ 345',
  },
  {
    name: 'Central African Republic',
    alpha2Code: 'CF',
    alpha3Code: 'CAF',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cf.svg',
    phoneCode: '+236',
  },
  {
    name: 'Chad',
    alpha2Code: 'TD',
    alpha3Code: 'TCD',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/td.svg',
    phoneCode: '+235',
  },
  {
    name: 'Chile',
    alpha2Code: 'CL',
    alpha3Code: 'CHL',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cl.svg',
    phoneCode: '+56',
  },
  {
    name: 'China',
    alpha2Code: 'CN',
    alpha3Code: 'CHN',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cn.svg',
    phoneCode: '+86',
  },
  {
    name: 'Christmas Island',
    alpha2Code: 'CX',
    alpha3Code: 'CXR',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cx.svg',
    phoneCode: '+61',
  },
  {
    name: 'Cocos (Keeling) Islands',
    alpha2Code: 'CC',
    alpha3Code: 'CCK',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cc.svg',
    phoneCode: '+61',
  },
  {
    name: 'Colombia',
    alpha2Code: 'CO',
    alpha3Code: 'COL',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/co.svg',
    phoneCode: '+57',
  },
  {
    name: 'Comoros',
    alpha2Code: 'KM',
    alpha3Code: 'COM',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/km.svg',
    phoneCode: '+269',
  },
  {
    name: 'Congo',
    alpha2Code: 'CG',
    alpha3Code: 'COG',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cg.svg',
    phoneCode: '+242',
  },
  {
    name: 'Congo (Democratic Republic of the)',
    alpha2Code: 'CD',
    alpha3Code: 'COD',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cd.svg',
    phoneCode: '+243',
  },
  {
    name: 'Cook Islands',
    alpha2Code: 'CK',
    alpha3Code: 'COK',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ck.svg',
    phoneCode: '+682',
  },
  {
    name: 'Costa Rica',
    alpha2Code: 'CR',
    alpha3Code: 'CRI',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cr.svg',
    phoneCode: '+506',
  },
  {
    name: 'Croatia',
    alpha2Code: 'HR',
    alpha3Code: 'HRV',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/hr.svg',
    phoneCode: '+385',
  },
  {
    name: 'Cuba',
    alpha2Code: 'CU',
    alpha3Code: 'CUB',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cu.svg',
    phoneCode: '+53',
  },
  {
    name: 'Curaçao',
    alpha2Code: 'CW',
    alpha3Code: 'CUW',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cw.svg',
  },
  {
    name: 'Cyprus',
    alpha2Code: 'CY',
    alpha3Code: 'CYP',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cy.svg',
    phoneCode: '+357',
  },
  {
    name: 'Czech Republic',
    alpha2Code: 'CZ',
    alpha3Code: 'CZE',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/cz.svg',
    phoneCode: '+420',
  },
  {
    name: 'Denmark',
    alpha2Code: 'DK',
    alpha3Code: 'DNK',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/dk.svg',
    phoneCode: '+45',
  },
  {
    name: 'Djibouti',
    alpha2Code: 'DJ',
    alpha3Code: 'DJI',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/dj.svg',
    phoneCode: '+253',
  },
  {
    name: 'Dominica',
    alpha2Code: 'DM',
    alpha3Code: 'DMA',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/dm.svg',
    phoneCode: '+1 767',
  },
  {
    name: 'Dominican Republic',
    alpha2Code: 'DO',
    alpha3Code: 'DOM',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/do.svg',
    phoneCode: '+1 849',
  },
  {
    name: 'Ecuador',
    alpha2Code: 'EC',
    alpha3Code: 'ECU',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ec.svg',
    phoneCode: '+593',
  },
  {
    name: 'Egypt',
    alpha2Code: 'EG',
    alpha3Code: 'EGY',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/eg.svg',
    phoneCode: '+20',
  },
  {
    name: 'El Salvador',
    alpha2Code: 'SV',
    alpha3Code: 'SLV',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sv.svg',
    phoneCode: '+503',
  },
  {
    name: 'Equatorial Guinea',
    alpha2Code: 'GQ',
    alpha3Code: 'GNQ',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gq.svg',
    phoneCode: '+240',
  },
  {
    name: 'Eritrea',
    alpha2Code: 'ER',
    alpha3Code: 'ERI',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/er.svg',
    phoneCode: '+291',
  },
  {
    name: 'Estonia',
    alpha2Code: 'EE',
    alpha3Code: 'EST',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ee.svg',
    phoneCode: '+372',
  },
  {
    name: 'Ethiopia',
    alpha2Code: 'ET',
    alpha3Code: 'ETH',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/et.svg',
    phoneCode: '+251',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    alpha2Code: 'FK',
    alpha3Code: 'FLK',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/fk.svg',
    phoneCode: '+500',
  },
  {
    name: 'Faroe Islands',
    alpha2Code: 'FO',
    alpha3Code: 'FRO',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/fo.svg',
    phoneCode: '+298',
  },
  {
    name: 'Fiji',
    alpha2Code: 'FJ',
    alpha3Code: 'FJI',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/fj.svg',
    phoneCode: '+679',
  },
  {
    name: 'Finland',
    alpha2Code: 'FI',
    alpha3Code: 'FIN',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/fi.svg',
    phoneCode: '+358',
  },
  {
    name: 'France',
    alpha2Code: 'FR',
    alpha3Code: 'FRA',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/fr.svg',
    phoneCode: '+33',
  },
  {
    name: 'French Guiana',
    alpha2Code: 'GF',
    alpha3Code: 'GUF',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gf.svg',
    phoneCode: '+594',
  },
  {
    name: 'French Polynesia',
    alpha2Code: 'PF',
    alpha3Code: 'PYF',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/pf.svg',
    phoneCode: '+689',
  },
  {
    name: 'French Southern Territories',
    alpha2Code: 'TF',
    alpha3Code: 'ATF',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tf.svg',
  },
  {
    name: 'Gabon',
    alpha2Code: 'GA',
    alpha3Code: 'GAB',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ga.svg',
    phoneCode: '+241',
  },
  {
    name: 'Gambia',
    alpha2Code: 'GM',
    alpha3Code: 'GMB',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gm.svg',
    phoneCode: '+220',
  },
  {
    name: 'Georgia',
    alpha2Code: 'GE',
    alpha3Code: 'GEO',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ge.svg',
    phoneCode: '+995',
  },
  {
    name: 'Germany',
    alpha2Code: 'DE',
    alpha3Code: 'DEU',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/de.svg',
    phoneCode: '+49',
  },
  {
    name: 'Ghana',
    alpha2Code: 'GH',
    alpha3Code: 'GHA',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gh.svg',
    phoneCode: '+233',
  },
  {
    name: 'Gibraltar',
    alpha2Code: 'GI',
    alpha3Code: 'GIB',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gi.svg',
    phoneCode: '+350',
  },
  {
    name: 'Greece',
    alpha2Code: 'GR',
    alpha3Code: 'GRC',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gr.svg',
    phoneCode: '+30',
  },
  {
    name: 'Greenland',
    alpha2Code: 'GL',
    alpha3Code: 'GRL',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gl.svg',
    phoneCode: '+299',
  },
  {
    name: 'Grenada',
    alpha2Code: 'GD',
    alpha3Code: 'GRD',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gd.svg',
    phoneCode: '+1 473',
  },
  {
    name: 'Guadeloupe',
    alpha2Code: 'GP',
    alpha3Code: 'GLP',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gp.svg',
    phoneCode: '+590',
  },
  {
    name: 'Guam',
    alpha2Code: 'GU',
    alpha3Code: 'GUM',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gu.svg',
    phoneCode: '+1 671',
  },
  {
    name: 'Guatemala',
    alpha2Code: 'GT',
    alpha3Code: 'GTM',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gt.svg',
    phoneCode: '+502',
  },
  {
    name: 'Guernsey',
    alpha2Code: 'GG',
    alpha3Code: 'GGY',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gg.svg',
    phoneCode: '+44',
  },
  {
    name: 'Guinea',
    alpha2Code: 'GN',
    alpha3Code: 'GIN',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gn.svg',
    phoneCode: '+224',
  },
  {
    name: 'Guinea-Bissau',
    alpha2Code: 'GW',
    alpha3Code: 'GNB',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gw.svg',
    phoneCode: '+245',
  },
  {
    name: 'Guyana',
    alpha2Code: 'GY',
    alpha3Code: 'GUY',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gy.svg',
    phoneCode: '+595',
  },
  {
    name: 'Haiti',
    alpha2Code: 'HT',
    alpha3Code: 'HTI',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ht.svg',
    phoneCode: '+509',
  },
  {
    name: 'Heard Island and McDonald Islands',
    alpha2Code: 'HM',
    alpha3Code: 'HMD',
    region: '',
    flag: 'https://firebasestorage.googleapis.com/v0/b/zporter-countries-flag/o/HM?alt=media&token=c9cce45b-6ff5-429e-9a15-819908701032',
  },
  {
    name: 'Holy See',
    alpha2Code: 'VA',
    alpha3Code: 'VAT',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/va.svg',
    phoneCode: '+379',
  },
  {
    name: 'Honduras',
    alpha2Code: 'HN',
    alpha3Code: 'HND',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/hn.svg',
    phoneCode: '+504',
  },
  {
    name: 'Hong Kong',
    alpha2Code: 'HK',
    alpha3Code: 'HKG',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/hk.svg',
    phoneCode: '+852',
  },
  {
    name: 'Hungary',
    alpha2Code: 'HU',
    alpha3Code: 'HUN',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/hu.svg',
    phoneCode: '+36',
  },
  {
    name: 'Iceland',
    alpha2Code: 'IS',
    alpha3Code: 'ISL',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/is.svg',
    phoneCode: '+354',
  },
  {
    name: 'India',
    alpha2Code: 'IN',
    alpha3Code: 'IND',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/in.svg',
    phoneCode: '+91',
  },
  {
    name: 'Indonesia',
    alpha2Code: 'ID',
    alpha3Code: 'IDN',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/id.svg',
    phoneCode: '+62',
  },
  {
    name: "Côte d'Ivoire",
    alpha2Code: 'CI',
    alpha3Code: 'CIV',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ci.svg',
    phoneCode: '+225',
  },
  {
    name: 'Iran (Islamic Republic of)',
    alpha2Code: 'IR',
    alpha3Code: 'IRN',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ir.svg',
    phoneCode: '+98',
  },
  {
    name: 'Iraq',
    alpha2Code: 'IQ',
    alpha3Code: 'IRQ',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/iq.svg',
    phoneCode: '+964',
  },
  {
    name: 'Ireland',
    alpha2Code: 'IE',
    alpha3Code: 'IRL',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ie.svg',
    phoneCode: '+353',
  },
  {
    name: 'Isle of Man',
    alpha2Code: 'IM',
    alpha3Code: 'IMN',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/im.svg',
    phoneCode: '+44',
  },
  {
    name: 'Israel',
    alpha2Code: 'IL',
    alpha3Code: 'ISR',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/il.svg',
    phoneCode: '+972',
  },
  {
    name: 'Italy',
    alpha2Code: 'IT',
    alpha3Code: 'ITA',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/it.svg',
    phoneCode: '+39',
  },
  {
    name: 'Jamaica',
    alpha2Code: 'JM',
    alpha3Code: 'JAM',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/jm.svg',
    phoneCode: '+1 876',
  },
  {
    name: 'Japan',
    alpha2Code: 'JP',
    alpha3Code: 'JPN',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/jp.svg',
    phoneCode: '+81',
  },
  {
    name: 'Jersey',
    alpha2Code: 'JE',
    alpha3Code: 'JEY',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/je.svg',
    phoneCode: '+44',
  },
  {
    name: 'Jordan',
    alpha2Code: 'JO',
    alpha3Code: 'JOR',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/jo.svg',
    phoneCode: '+962',
  },
  {
    name: 'Kazakhstan',
    alpha2Code: 'KZ',
    alpha3Code: 'KAZ',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/kz.svg',
    phoneCode: '+7 7',
  },
  {
    name: 'Kenya',
    alpha2Code: 'KE',
    alpha3Code: 'KEN',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ke.svg',
    phoneCode: '+254',
  },
  {
    name: 'Kiribati',
    alpha2Code: 'KI',
    alpha3Code: 'KIR',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ki.svg',
    phoneCode: '+686',
  },
  {
    name: 'Kuwait',
    alpha2Code: 'KW',
    alpha3Code: 'KWT',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/kw.svg',
    phoneCode: '+965',
  },
  {
    name: 'Kyrgyzstan',
    alpha2Code: 'KG',
    alpha3Code: 'KGZ',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/kg.svg',
    phoneCode: '+996',
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2Code: 'LA',
    alpha3Code: 'LAO',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/la.svg',
    phoneCode: '+856',
  },
  {
    name: 'Latvia',
    alpha2Code: 'LV',
    alpha3Code: 'LVA',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/lv.svg',
    phoneCode: '+371',
  },
  {
    name: 'Lebanon',
    alpha2Code: 'LB',
    alpha3Code: 'LBN',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/lb.svg',
    phoneCode: '+961',
  },
  {
    name: 'Lesotho',
    alpha2Code: 'LS',
    alpha3Code: 'LSO',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ls.svg',
    phoneCode: '+266',
  },
  {
    name: 'Liberia',
    alpha2Code: 'LR',
    alpha3Code: 'LBR',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/lr.svg',
    phoneCode: '+231',
  },
  {
    name: 'Libya',
    alpha2Code: 'LY',
    alpha3Code: 'LBY',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ly.svg',
    phoneCode: '+218',
  },
  {
    name: 'Liechtenstein',
    alpha2Code: 'LI',
    alpha3Code: 'LIE',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/li.svg',
    phoneCode: '+423',
  },
  {
    name: 'Lithuania',
    alpha2Code: 'LT',
    alpha3Code: 'LTU',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/lt.svg',
    phoneCode: '+370',
  },
  {
    name: 'Luxembourg',
    alpha2Code: 'LU',
    alpha3Code: 'LUX',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/lu.svg',
    phoneCode: '+352',
  },
  {
    name: 'Macao',
    alpha2Code: 'MO',
    alpha3Code: 'MAC',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mo.svg',
    phoneCode: '+853',
  },
  {
    name: 'Macedonia (the former Yugoslav Republic of)',
    alpha2Code: 'MK',
    alpha3Code: 'MKD',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mk.svg',
    phoneCode: '+389',
  },
  {
    name: 'Madagascar',
    alpha2Code: 'MG',
    alpha3Code: 'MDG',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mg.svg',
    phoneCode: '+261',
  },
  {
    name: 'Malawi',
    alpha2Code: 'MW',
    alpha3Code: 'MWI',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mw.svg',
    phoneCode: '+265',
  },
  {
    name: 'Malaysia',
    alpha2Code: 'MY',
    alpha3Code: 'MYS',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/my.svg',
    phoneCode: '+60',
  },
  {
    name: 'Maldives',
    alpha2Code: 'MV',
    alpha3Code: 'MDV',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mv.svg',
    phoneCode: '+960',
  },
  {
    name: 'Mali',
    alpha2Code: 'ML',
    alpha3Code: 'MLI',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ml.svg',
    phoneCode: '+223',
  },
  {
    name: 'Malta',
    alpha2Code: 'MT',
    alpha3Code: 'MLT',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mt.svg',
    phoneCode: '+356',
  },
  {
    name: 'Marshall Islands',
    alpha2Code: 'MH',
    alpha3Code: 'MHL',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mh.svg',
    phoneCode: '+692',
  },
  {
    name: 'Martinique',
    alpha2Code: 'MQ',
    alpha3Code: 'MTQ',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mq.svg',
    phoneCode: '+596',
  },
  {
    name: 'Mauritania',
    alpha2Code: 'MR',
    alpha3Code: 'MRT',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mr.svg',
    phoneCode: '+222',
  },
  {
    name: 'Mauritius',
    alpha2Code: 'MU',
    alpha3Code: 'MUS',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mu.svg',
    phoneCode: '+230',
  },
  {
    name: 'Mayotte',
    alpha2Code: 'YT',
    alpha3Code: 'MYT',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/yt.svg',
    phoneCode: '+262',
  },
  {
    name: 'Mexico',
    alpha2Code: 'MX',
    alpha3Code: 'MEX',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mx.svg',
    phoneCode: '+52',
  },
  {
    name: 'Micronesia (Federated States of)',
    alpha2Code: 'FM',
    alpha3Code: 'FSM',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/fm.svg',
    phoneCode: '+691',
  },
  {
    name: 'Moldova (Republic of)',
    alpha2Code: 'MD',
    alpha3Code: 'MDA',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/md.svg',
    phoneCode: '+373',
  },
  {
    name: 'Monaco',
    alpha2Code: 'MC',
    alpha3Code: 'MCO',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mc.svg',
    phoneCode: '+377',
  },
  {
    name: 'Mongolia',
    alpha2Code: 'MN',
    alpha3Code: 'MNG',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mn.svg',
    phoneCode: '+976',
  },
  {
    name: 'Montenegro',
    alpha2Code: 'ME',
    alpha3Code: 'MNE',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/me.svg',
    phoneCode: '+382',
  },
  {
    name: 'Montserrat',
    alpha2Code: 'MS',
    alpha3Code: 'MSR',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ms.svg',
    phoneCode: '+1664',
  },
  {
    name: 'Morocco',
    alpha2Code: 'MA',
    alpha3Code: 'MAR',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ma.svg',
    phoneCode: '+212',
  },
  {
    name: 'Mozambique',
    alpha2Code: 'MZ',
    alpha3Code: 'MOZ',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mz.svg',
    phoneCode: '+258',
  },
  {
    name: 'Myanmar',
    alpha2Code: 'MM',
    alpha3Code: 'MMR',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mm.svg',
    phoneCode: '+95',
  },
  {
    name: 'Namibia',
    alpha2Code: 'NA',
    alpha3Code: 'NAM',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/na.svg',
    phoneCode: '+264',
  },
  {
    name: 'Nauru',
    alpha2Code: 'NR',
    alpha3Code: 'NRU',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/nr.svg',
    phoneCode: '+674',
  },
  {
    name: 'Nepal',
    alpha2Code: 'NP',
    alpha3Code: 'NPL',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/np.svg',
    phoneCode: '+977',
  },
  {
    name: 'Netherlands',
    alpha2Code: 'NL',
    alpha3Code: 'NLD',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/nl.svg',
    phoneCode: '+31',
  },
  {
    name: 'New Caledonia',
    alpha2Code: 'NC',
    alpha3Code: 'NCL',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/nc.svg',
    phoneCode: '+687',
  },
  {
    name: 'New Zealand',
    alpha2Code: 'NZ',
    alpha3Code: 'NZL',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/nz.svg',
    phoneCode: '+64',
  },
  {
    name: 'Nicaragua',
    alpha2Code: 'NI',
    alpha3Code: 'NIC',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ni.svg',
    phoneCode: '+505',
  },
  {
    name: 'Niger',
    alpha2Code: 'NE',
    alpha3Code: 'NER',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ne.svg',
    phoneCode: '+227',
  },
  {
    name: 'Nigeria',
    alpha2Code: 'NG',
    alpha3Code: 'NGA',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ng.svg',
    phoneCode: '+234',
  },
  {
    name: 'Niue',
    alpha2Code: 'NU',
    alpha3Code: 'NIU',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/nu.svg',
    phoneCode: '+683',
  },
  {
    name: 'Norfolk Island',
    alpha2Code: 'NF',
    alpha3Code: 'NFK',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/nf.svg',
    phoneCode: '+672',
  },
  {
    name: "Korea (Democratic People's Republic of)",
    alpha2Code: 'KP',
    alpha3Code: 'PRK',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/kp.svg',
    phoneCode: '+850',
  },
  {
    name: 'Northern Mariana Islands',
    alpha2Code: 'MP',
    alpha3Code: 'MNP',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mp.svg',
    phoneCode: '+1 670',
  },
  {
    name: 'Norway',
    alpha2Code: 'NO',
    alpha3Code: 'NOR',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/no.svg',
    phoneCode: '+47',
  },
  {
    name: 'Oman',
    alpha2Code: 'OM',
    alpha3Code: 'OMN',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/om.svg',
    phoneCode: '+968',
  },
  {
    name: 'Pakistan',
    alpha2Code: 'PK',
    alpha3Code: 'PAK',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/pk.svg',
    phoneCode: '+92',
  },
  {
    name: 'Palau',
    alpha2Code: 'PW',
    alpha3Code: 'PLW',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/pw.svg',
    phoneCode: '+680',
  },
  {
    name: 'Palestine, State of',
    alpha2Code: 'PS',
    alpha3Code: 'PSE',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ps.svg',
    phoneCode: '+970',
  },
  {
    name: 'Panama',
    alpha2Code: 'PA',
    alpha3Code: 'PAN',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/pa.svg',
    phoneCode: '+507',
  },
  {
    name: 'Papua New Guinea',
    alpha2Code: 'PG',
    alpha3Code: 'PNG',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/pg.svg',
    phoneCode: '+675',
  },
  {
    name: 'Paraguay',
    alpha2Code: 'PY',
    alpha3Code: 'PRY',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/py.svg',
    phoneCode: '+595',
  },
  {
    name: 'Peru',
    alpha2Code: 'PE',
    alpha3Code: 'PER',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/pe.svg',
    phoneCode: '+51',
  },
  {
    name: 'Philippines',
    alpha2Code: 'PH',
    alpha3Code: 'PHL',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ph.svg',
    phoneCode: '+63',
  },
  {
    name: 'Pitcairn',
    alpha2Code: 'PN',
    alpha3Code: 'PCN',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/pn.svg',
    phoneCode: '+872',
  },
  {
    name: 'Poland',
    alpha2Code: 'PL',
    alpha3Code: 'POL',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/pl.svg',
    phoneCode: '+48',
  },
  {
    name: 'Portugal',
    alpha2Code: 'PT',
    alpha3Code: 'PRT',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/pt.svg',
    phoneCode: '+351',
  },
  {
    name: 'Puerto Rico',
    alpha2Code: 'PR',
    alpha3Code: 'PRI',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/pr.svg',
    phoneCode: '+1 939',
  },
  {
    name: 'Qatar',
    alpha2Code: 'QA',
    alpha3Code: 'QAT',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/qa.svg',
    phoneCode: '+974',
  },
  {
    name: 'Republic of Kosovo',
    alpha2Code: 'XK',
    alpha3Code: 'KOS',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/xk.svg',
  },
  {
    name: 'Réunion',
    alpha2Code: 'RE',
    alpha3Code: 'REU',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/re.svg',
    phoneCode: '+262',
  },
  {
    name: 'Romania',
    alpha2Code: 'RO',
    alpha3Code: 'ROU',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ro.svg',
    phoneCode: '+40',
  },
  {
    name: 'Russian Federation',
    alpha2Code: 'RU',
    alpha3Code: 'RUS',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ru.svg',
    phoneCode: '+7',
  },
  {
    name: 'Rwanda',
    alpha2Code: 'RW',
    alpha3Code: 'RWA',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/rw.svg',
    phoneCode: '+250',
  },
  {
    name: 'Saint Barthélemy',
    alpha2Code: 'BL',
    alpha3Code: 'BLM',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/bl.svg',
    phoneCode: '+590',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    alpha2Code: 'SH',
    alpha3Code: 'SHN',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sh.svg',
    phoneCode: '+290',
  },
  {
    name: 'Saint Kitts and Nevis',
    alpha2Code: 'KN',
    alpha3Code: 'KNA',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/kn.svg',
    phoneCode: '+1 869',
  },
  {
    name: 'Saint Lucia',
    alpha2Code: 'LC',
    alpha3Code: 'LCA',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/lc.svg',
    phoneCode: '+1 758',
  },
  {
    name: 'Saint Martin (French part)',
    alpha2Code: 'MF',
    alpha3Code: 'MAF',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/mf.svg',
    phoneCode: '+590',
  },
  {
    name: 'Saint Pierre and Miquelon',
    alpha2Code: 'PM',
    alpha3Code: 'SPM',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/pm.svg',
    phoneCode: '+508',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    alpha2Code: 'VC',
    alpha3Code: 'VCT',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/vc.svg',
    phoneCode: '+1 784',
  },
  {
    name: 'Samoa',
    alpha2Code: 'WS',
    alpha3Code: 'WSM',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ws.svg',
    phoneCode: '+685',
  },
  {
    name: 'San Marino',
    alpha2Code: 'SM',
    alpha3Code: 'SMR',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sm.svg',
    phoneCode: '+378',
  },
  {
    name: 'Sao Tome and Principe',
    alpha2Code: 'ST',
    alpha3Code: 'STP',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/st.svg',
    phoneCode: '+239',
  },
  {
    name: 'Saudi Arabia',
    alpha2Code: 'SA',
    alpha3Code: 'SAU',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sa.svg',
    phoneCode: '+966',
  },
  {
    name: 'Senegal',
    alpha2Code: 'SN',
    alpha3Code: 'SEN',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sn.svg',
    phoneCode: '+221',
  },
  {
    name: 'Serbia',
    alpha2Code: 'RS',
    alpha3Code: 'SRB',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/rs.svg',
    phoneCode: '+381',
  },
  {
    name: 'Seychelles',
    alpha2Code: 'SC',
    alpha3Code: 'SYC',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sc.svg',
    phoneCode: '+248',
  },
  {
    name: 'Sierra Leone',
    alpha2Code: 'SL',
    alpha3Code: 'SLE',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sl.svg',
    phoneCode: '+232',
  },
  {
    name: 'Singapore',
    alpha2Code: 'SG',
    alpha3Code: 'SGP',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sg.svg',
    phoneCode: '+65',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    alpha2Code: 'SX',
    alpha3Code: 'SXM',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sx.svg',
  },
  {
    name: 'Slovakia',
    alpha2Code: 'SK',
    alpha3Code: 'SVK',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sk.svg',
    phoneCode: '+421',
  },
  {
    name: 'Slovenia',
    alpha2Code: 'SI',
    alpha3Code: 'SVN',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/si.svg',
    phoneCode: '+386',
  },
  {
    name: 'Solomon Islands',
    alpha2Code: 'SB',
    alpha3Code: 'SLB',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sb.svg',
    phoneCode: '+677',
  },
  {
    name: 'Somalia',
    alpha2Code: 'SO',
    alpha3Code: 'SOM',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/so.svg',
    phoneCode: '+252',
  },
  {
    name: 'South Africa',
    alpha2Code: 'ZA',
    alpha3Code: 'ZAF',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/za.svg',
    phoneCode: '+27',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    alpha2Code: 'GS',
    alpha3Code: 'SGS',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gs.svg',
    phoneCode: '+500',
  },
  {
    name: 'Korea (Republic of)',
    alpha2Code: 'KR',
    alpha3Code: 'KOR',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/kr.svg',
    phoneCode: '+82',
  },
  {
    name: 'South Sudan',
    alpha2Code: 'SS',
    alpha3Code: 'SSD',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ss.svg',
  },
  {
    name: 'Spain',
    alpha2Code: 'ES',
    alpha3Code: 'ESP',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/es.svg',
    phoneCode: '+34',
  },
  {
    name: 'Sri Lanka',
    alpha2Code: 'LK',
    alpha3Code: 'LKA',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/lk.svg',
    phoneCode: '+94',
  },
  {
    name: 'Sudan',
    alpha2Code: 'SD',
    alpha3Code: 'SDN',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sd.svg',
    phoneCode: '+249',
  },
  {
    name: 'Suriname',
    alpha2Code: 'SR',
    alpha3Code: 'SUR',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sr.svg',
    phoneCode: '+597',
  },
  {
    name: 'Svalbard and Jan Mayen',
    alpha2Code: 'SJ',
    alpha3Code: 'SJM',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sj.svg',
    phoneCode: '+47',
  },
  {
    name: 'Swaziland',
    alpha2Code: 'SZ',
    alpha3Code: 'SWZ',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sz.svg',
    phoneCode: '+268',
  },
  {
    name: 'Sweden',
    alpha2Code: 'SE',
    alpha3Code: 'SWE',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/se.svg',
    phoneCode: '+46',
  },
  {
    name: 'Switzerland',
    alpha2Code: 'CH',
    alpha3Code: 'CHE',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ch.svg',
    phoneCode: '+41',
  },
  {
    name: 'Syrian Arab Republic',
    alpha2Code: 'SY',
    alpha3Code: 'SYR',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/sy.svg',
    phoneCode: '+963',
  },
  {
    name: 'Taiwan',
    alpha2Code: 'TW',
    alpha3Code: 'TWN',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tw.svg',
    phoneCode: '+886',
  },
  {
    name: 'Tajikistan',
    alpha2Code: 'TJ',
    alpha3Code: 'TJK',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tj.svg',
    phoneCode: '+992',
  },
  {
    name: 'Tanzania, United Republic of',
    alpha2Code: 'TZ',
    alpha3Code: 'TZA',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tz.svg',
    phoneCode: '+255',
  },
  {
    name: 'Thailand',
    alpha2Code: 'TH',
    alpha3Code: 'THA',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/th.svg',
    phoneCode: '+66',
  },
  {
    name: 'Timor-Leste',
    alpha2Code: 'TL',
    alpha3Code: 'TLS',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tl.svg',
    phoneCode: '+670',
  },
  {
    name: 'Togo',
    alpha2Code: 'TG',
    alpha3Code: 'TGO',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tg.svg',
    phoneCode: '+228',
  },
  {
    name: 'Tokelau',
    alpha2Code: 'TK',
    alpha3Code: 'TKL',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tk.svg',
    phoneCode: '+690',
  },
  {
    name: 'Tonga',
    alpha2Code: 'TO',
    alpha3Code: 'TON',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/to.svg',
    phoneCode: '+676',
  },
  {
    name: 'Trinidad and Tobago',
    alpha2Code: 'TT',
    alpha3Code: 'TTO',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tt.svg',
    phoneCode: '+1 868',
  },
  {
    name: 'Tunisia',
    alpha2Code: 'TN',
    alpha3Code: 'TUN',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tn.svg',
    phoneCode: '+216',
  },
  {
    name: 'Turkey',
    alpha2Code: 'TR',
    alpha3Code: 'TUR',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tr.svg',
    phoneCode: '+90',
  },
  {
    name: 'Turkmenistan',
    alpha2Code: 'TM',
    alpha3Code: 'TKM',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tm.svg',
    phoneCode: '+993',
  },
  {
    name: 'Turks and Caicos Islands',
    alpha2Code: 'TC',
    alpha3Code: 'TCA',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tc.svg',
    phoneCode: '+1 649',
  },
  {
    name: 'Tuvalu',
    alpha2Code: 'TV',
    alpha3Code: 'TUV',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/tv.svg',
    phoneCode: '+688',
  },
  {
    name: 'Uganda',
    alpha2Code: 'UG',
    alpha3Code: 'UGA',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ug.svg',
    phoneCode: '+256',
  },
  {
    name: 'Ukraine',
    alpha2Code: 'UA',
    alpha3Code: 'UKR',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ua.svg',
    phoneCode: '+380',
  },
  {
    name: 'United Arab Emirates',
    alpha2Code: 'AE',
    alpha3Code: 'ARE',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ae.svg',
    phoneCode: '+971',
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    alpha2Code: 'GB',
    alpha3Code: 'GBR',
    region: 'Europe',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/gb.svg',
    phoneCode: '+44',
  },
  {
    name: 'United States of America',
    alpha2Code: 'US',
    alpha3Code: 'USA',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/us.svg',
    phoneCode: '+1',
  },
  {
    name: 'Uruguay',
    alpha2Code: 'UY',
    alpha3Code: 'URY',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/uy.svg',
    phoneCode: '+598',
  },
  {
    name: 'Uzbekistan',
    alpha2Code: 'UZ',
    alpha3Code: 'UZB',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/uz.svg',
    phoneCode: '+998',
  },
  {
    name: 'Vanuatu',
    alpha2Code: 'VU',
    alpha3Code: 'VUT',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/vu.svg',
    phoneCode: '+678',
  },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    alpha2Code: 'VE',
    alpha3Code: 'VEN',
    region: 'Americas',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ve.svg',
    phoneCode: '+58',
  },
  {
    name: 'Viet Nam',
    alpha2Code: 'VN',
    alpha3Code: 'VNM',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/vn.svg',
    phoneCode: '+84',
  },
  {
    name: 'Wallis and Futuna',
    alpha2Code: 'WF',
    alpha3Code: 'WLF',
    region: 'Oceania',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/wf.svg',
    phoneCode: '+681',
  },
  {
    name: 'Western Sahara',
    alpha2Code: 'EH',
    alpha3Code: 'ESH',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/eh.svg',
  },
  {
    name: 'Yemen',
    alpha2Code: 'YE',
    alpha3Code: 'YEM',
    region: 'Asia',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/ye.svg',
    phoneCode: '+967',
  },
  {
    name: 'Zambia',
    alpha2Code: 'ZM',
    alpha3Code: 'ZMB',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/zm.svg',
    phoneCode: '+260',
  },
  {
    name: 'Zimbabwe',
    alpha2Code: 'ZW',
    alpha3Code: 'ZWE',
    region: 'Africa',
    flag: 'https://static.dwcdn.net/css/flag-icons/flags/1x1/zw.svg',
    phoneCode: '+263',
  },
];
